// AUTO-GENERATED by samples/android-demo/scripts/collate-demos.sh — DO NOT EDIT.
//
// This file is regenerated from every `*Fragment.kt` under
// `src/main/java/io/github/sceneview/demo/fragments/`. To add or remove a demo,
// add or remove a fragment file and re-run the collator; never edit this file
// by hand.
//
// Fragments are sorted by demo id so two parallel PRs adding two different
// demos never collide on this file (issue #1797).
package io.github.sceneview.demo.fragments

import androidx.compose.runtime.Composable
import io.github.sceneview.demo.DemoEntry

/**
 * Generated aggregate of every [DemoFragment] declared under
 * `io.github.sceneview.demo.fragments`. Drives [io.github.sceneview.demo.ALL_DEMOS]
 * and [io.github.sceneview.demo.DemoRouter]. Regenerate with
 * `samples/android-demo/scripts/collate-demos.sh`.
 */
object GeneratedDemos {
    /** All fragments, sorted by demo id. */
    val fragments: List<DemoFragment> = listOf(
        AnimationFragment,
        ArCloudAnchorFragment,
        ArDepthColliderFragment,
        ArDepthOcclusionFragment,
        ArDepthOfFieldFragment,
        ArDepthVisualizationFragment,
        ArFaceFragment,
        ArFogFragment,
        ArHandTrackingFragment,
        ArImageFragment,
        ArImageStabilizationFragment,
        ArInstantPlacementFragment,
        ArMlObjectLabelFragment,
        ArOrbitalFragment,
        ArPlacementFragment,
        ArPoseFragment,
        ArRawDepthPointCloudFragment,
        ArRecordPlaybackFragment,
        ArRerunFragment,
        ArRooftopFragment,
        ArSceneSemanticsFragment,
        ArStreetscapeFragment,
        ArTerrainFragment,
        BillboardFragment,
        CameraControlsFragment,
        CollisionFragment,
        CustomMeshFragment,
        DebugOverlayFragment,
        DoublePendulumFragment,
        DynamicSkyFragment,
        EnvironmentFragment,
        FogFragment,
        GeometryFragment,
        GestureEditingFragment,
        ImageFragment,
        LightingFragment,
        LinesPathsFragment,
        MaterialsFragment,
        ModelViewerFragment,
        MovableLightFragment,
        MultiModelFragment,
        OcclusionMaterialFragment,
        PhysicsFragment,
        PostProcessingFragment,
        ReflectionProbesFragment,
        SceneGalleryFragment,
        SecondaryCameraFragment,
        ShapeFragment,
        SpatialAudioFragment,
        TextFragment,
        TextureStreamingFragment,
        VideoFragment,
        ViewNodeFragment,
    )

    /** Convenience: every demo's metadata, in the same order as [fragments]. */
    val all: List<DemoEntry> = fragments.map { it.entry }

    /**
     * Returns the composable for the demo with the given [id], or `null` if no
     * fragment registers that id. The caller (typically
     * [io.github.sceneview.demo.DemoRouter]) is expected to handle the null
     * case by falling back to a placeholder screen.
     */
    @Composable
    fun Screen(id: String, onBack: () -> Unit): Boolean {
        when (id) {
            "animation" -> AnimationFragment.Screen(onBack)
            "ar-cloud-anchor" -> ArCloudAnchorFragment.Screen(onBack)
            "ar-depth-collider" -> ArDepthColliderFragment.Screen(onBack)
            "ar-depth-occlusion" -> ArDepthOcclusionFragment.Screen(onBack)
            "ar-depth-of-field" -> ArDepthOfFieldFragment.Screen(onBack)
            "ar-depth-visualization" -> ArDepthVisualizationFragment.Screen(onBack)
            "ar-face" -> ArFaceFragment.Screen(onBack)
            "ar-fog" -> ArFogFragment.Screen(onBack)
            "ar-hand-tracking" -> ArHandTrackingFragment.Screen(onBack)
            "ar-image" -> ArImageFragment.Screen(onBack)
            "ar-image-stabilization" -> ArImageStabilizationFragment.Screen(onBack)
            "ar-instant-placement" -> ArInstantPlacementFragment.Screen(onBack)
            "ar-ml-object-label" -> ArMlObjectLabelFragment.Screen(onBack)
            "ar-orbital" -> ArOrbitalFragment.Screen(onBack)
            "ar-placement" -> ArPlacementFragment.Screen(onBack)
            "ar-pose" -> ArPoseFragment.Screen(onBack)
            "ar-raw-depth-point-cloud" -> ArRawDepthPointCloudFragment.Screen(onBack)
            "ar-record-playback" -> ArRecordPlaybackFragment.Screen(onBack)
            "ar-rerun" -> ArRerunFragment.Screen(onBack)
            "ar-rooftop" -> ArRooftopFragment.Screen(onBack)
            "ar-scene-semantics" -> ArSceneSemanticsFragment.Screen(onBack)
            "ar-streetscape" -> ArStreetscapeFragment.Screen(onBack)
            "ar-terrain" -> ArTerrainFragment.Screen(onBack)
            "billboard" -> BillboardFragment.Screen(onBack)
            "camera-controls" -> CameraControlsFragment.Screen(onBack)
            "collision" -> CollisionFragment.Screen(onBack)
            "custom-mesh" -> CustomMeshFragment.Screen(onBack)
            "debug-overlay" -> DebugOverlayFragment.Screen(onBack)
            "double-pendulum" -> DoublePendulumFragment.Screen(onBack)
            "dynamic-sky" -> DynamicSkyFragment.Screen(onBack)
            "environment" -> EnvironmentFragment.Screen(onBack)
            "fog" -> FogFragment.Screen(onBack)
            "geometry" -> GeometryFragment.Screen(onBack)
            "gesture-editing" -> GestureEditingFragment.Screen(onBack)
            "image" -> ImageFragment.Screen(onBack)
            "lighting" -> LightingFragment.Screen(onBack)
            "lines-paths" -> LinesPathsFragment.Screen(onBack)
            "materials" -> MaterialsFragment.Screen(onBack)
            "model-viewer" -> ModelViewerFragment.Screen(onBack)
            "movable-light" -> MovableLightFragment.Screen(onBack)
            "multi-model" -> MultiModelFragment.Screen(onBack)
            "occlusion-material" -> OcclusionMaterialFragment.Screen(onBack)
            "physics" -> PhysicsFragment.Screen(onBack)
            "post-processing" -> PostProcessingFragment.Screen(onBack)
            "reflection-probes" -> ReflectionProbesFragment.Screen(onBack)
            "scene-gallery" -> SceneGalleryFragment.Screen(onBack)
            "secondary-camera" -> SecondaryCameraFragment.Screen(onBack)
            "shape" -> ShapeFragment.Screen(onBack)
            "spatial-audio" -> SpatialAudioFragment.Screen(onBack)
            "text" -> TextFragment.Screen(onBack)
            "texture-streaming" -> TextureStreamingFragment.Screen(onBack)
            "video" -> VideoFragment.Screen(onBack)
            "view-node" -> ViewNodeFragment.Screen(onBack)
            else -> return false
        }
        return true
    }
}
