package io.github.sceneview.demo.common

import android.annotation.SuppressLint
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.blur
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import io.github.sceneview.SurfaceType
import io.github.sceneview.demo.DemoSettings
import kotlinx.coroutines.delay

/**
 * QA-only synthetic camera backdrop for the AR demos (#3308).
 *
 * The arm64 ARCore emulator has no camera HAL, so `onSessionUpdated` never fires and every
 * AR screenshot lands on a flat black surface. When the backdrop is **enabled**
 * (`--ez qa_backdrop true`, or `qa_mode` when the extra is absent) the AR surface is made
 * translucent and, once [QA_BACKDROP_TIMEOUT_MS] elapse without a camera frame, a blurred
 * room photo is drawn beneath it so the chrome, coaching UI and placed models read like a
 * real AR session. A real camera (or an MP4 playback) that delivers a frame switches the
 * backdrop off again, so behaviour on a device is unchanged.
 *
 * The photos live in the **debug** source set (`qa_backdrop_<n>.webp`, generated by
 * `tools/demo-previews/backdrops.py`) and are resolved by name so the release build,
 * which ships none of them, still compiles and simply never draws one.
 */
const val QA_BACKDROP_TIMEOUT_MS = 1_500L

/** `true` when the QA backdrop may kick in: the explicit extra wins, else follow qa_mode. */
fun qaCameraBackdropEnabled(): Boolean = DemoSettings.qaBackdrop ?: DemoSettings.qaMode

/**
 * Surface to render the AR scene on. A `SurfaceView` punches a hole through the window, so
 * nothing composed beneath it can show through a translucent frame; a `TextureView`
 * composites like any other view. Only the QA backdrop pays that cost.
 */
fun qaCameraBackdropSurfaceType(): SurfaceType =
    if (qaCameraBackdropEnabled()) SurfaceType.TextureSurface else SurfaceType.Surface

/**
 * `true` while the backdrop should be drawn: enabled, and no camera frame has arrived
 * within [QA_BACKDROP_TIMEOUT_MS] of composition (or since the last one).
 */
@Composable
fun rememberQaCameraBackdropActive(cameraReady: Boolean): Boolean {
    val enabled = qaCameraBackdropEnabled()
    var active by remember { mutableStateOf(false) }
    LaunchedEffect(enabled, cameraReady) {
        if (enabled && !cameraReady) {
            delay(QA_BACKDROP_TIMEOUT_MS)
            active = true
        } else {
            active = false
        }
    }
    return active
}

/**
 * Draws the backdrop picked deterministically from [seed] (usually the demo id) so the same
 * demo always screenshots on the same room. No-op when the debug resources are absent.
 */
@SuppressLint("DiscouragedApi")
@Composable
fun QaCameraBackdrop(seed: String, modifier: Modifier = Modifier) {
    val context = LocalContext.current
    val resIds = remember(context) {
        generateSequence(1) { it + 1 }
            .map { context.resources.getIdentifier("qa_backdrop_$it", "drawable", context.packageName) }
            .takeWhile { it != 0 }
            .toList()
    }
    if (resIds.isEmpty()) return
    val resId = resIds[Math.floorMod(seed.hashCode(), resIds.size)]
    Image(
        painter = painterResource(resId),
        contentDescription = null,
        contentScale = ContentScale.Crop,
        modifier = modifier.fillMaxSize().blur(2.dp),
    )
}
