package io.github.sceneview.ar.rerun

import android.util.Log
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.google.ar.core.Anchor
import com.google.ar.core.Frame
import com.google.ar.core.HitResult
import com.google.ar.core.Plane
import com.google.ar.core.Pose
import com.google.ar.core.Session
import com.google.ar.core.TrackingState
import io.github.sceneview.ar.arcore.getUpdatedPlanes
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.launch
import java.io.BufferedReader
import java.io.BufferedWriter
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.net.InetSocketAddress
import java.net.Socket
import java.util.concurrent.CopyOnWriteArrayList

/**
 * Streams ARCore session data to a Rerun viewer over TCP using the
 * JSON-lines wire format defined by [RerunWireFormat].
 *
 * ### Why this exists
 *
 * Rerun has no native Kotlin SDK. The bridge emits one JSON object per line
 * and a tiny Python sidecar (`tools/rerun-bridge.py`, generated by the
 * `rerun-3d-mcp` package) reads the socket and re-logs each event into the
 * Rerun viewer as the matching archetype (`Transform3D`, `Points3D`,
 * `LineStrips3D`, …). The developer runs the sidecar + `rerun` on their
 * dev machine, then `adb reverse tcp:9876 tcp:9876` and launches the app.
 *
 * ### Threading
 *
 * All I/O runs on [Dispatchers.IO] via a dedicated supervisor scope. The
 * public `log*` methods are non-blocking: each event is enqueued on a
 * rendezvous [Channel] with `CONFLATED` behaviour so the newest event wins
 * and backpressure drops frames silently. This is the only correct choice
 * for a render-loop callback — Filament's main-thread contract forbids
 * blocking inside `onSessionUpdated`.
 *
 * That queue belongs to the **connection**, not to the bridge: [connect]
 * installs a fresh one, so events logged while disconnected are dropped
 * rather than replayed onto the next connection. See [connect].
 *
 * ### Usage
 *
 * Prefer the composable [rememberRerunBridge] helper; this class is public
 * so non-Compose hosts (plain `View`s, unit tests) can still use it.
 *
 * ```kotlin
 * val bridge = RerunBridge(host = "127.0.0.1", port = 9876, rateHz = 10)
 * bridge.connect()
 * try {
 *     arSession.onFrame { frame -> bridge.logFrame(session, frame) }
 * } finally {
 *     bridge.disconnect()
 * }
 * ```
 *
 * @param host Host to connect to. Use `127.0.0.1` with `adb reverse tcp:$port tcp:$port`.
 * @param port TCP port the Python sidecar listens on.
 * @param rateHz Maximum number of frames logged per second. Later events are dropped.
 *               Default: 10 Hz. Set to `0` to disable throttling.
 * @param tag Logcat tag used for connection errors.
 */
public class RerunBridge
@JvmOverloads
public constructor(
    private val host: String = DEFAULT_HOST,
    private val port: Int = DEFAULT_PORT,
    private val rateHz: Int = DEFAULT_RATE_HZ,
    private val tag: String = "RerunBridge",
) {

    public companion object {
        public const val DEFAULT_HOST: String = "127.0.0.1"
        public const val DEFAULT_PORT: Int = 9876
        public const val DEFAULT_RATE_HZ: Int = 10
    }

    /**
     * Result of [requestSaveAndShare] — either the sidecar wrote a `.rrd`
     * file (`success = true` and `path` / `viewerUrl` populated) or it
     * couldn't (`success = false` with a human-readable [reason]).
     *
     * `viewerUrl` is the SceneView Rerun page pre-filled with the recording
     * location. The underlying URL usually points at a `file://` path on the
     * dev machine which most browsers won't fetch from an HTTPS page — drop
     * the `.rrd` onto [`sceneview.github.io/rerun/`](https://sceneview.github.io/rerun/)
     * to render it in-place, or re-host the file on a public URL first.
     */
    public data class ShareResult(
        public val success: Boolean,
        public val path: String?,
        public val viewerUrl: String?,
        public val events: Int,
        public val reason: String?,
    )

    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    // Conflated channel: the sender never blocks; a new event replaces any
    // pending one. This gives us drop-on-backpressure semantics for free.
    //
    // ONE CHANNEL PER CONNECTION, swapped by [connect]. A single bridge-wide
    // channel silently ate the first event of every reconnect (#2777): the
    // outgoing writer is still parked in `receive` when disconnect() cancels
    // it, and a `trySend` that lands before the cancellation is processed is
    // handed straight to that dead receiver. With no `onUndeliveredElement`
    // hook the element is then dropped on the floor — never buffered, so the
    // incoming writer never sees it and the fresh socket looks mute. Giving
    // each connection its own channel makes that structurally impossible:
    // an event enqueued after connect() returns can only ever reach the
    // writer that connect() just started.
    //
    // Volatile because `enqueue` runs on the render thread while `connect`
    // swaps the reference from the caller's thread.
    @Volatile private var outbox = Channel<String>(capacity = Channel.CONFLATED)

    @Volatile private var socket: Socket? = null
    @Volatile private var writer: BufferedWriter? = null
    @Volatile private var writerJob: Job? = null
    @Volatile private var readerJob: Job? = null
    @Volatile private var lastEmitNanos: Long = 0L

    // ── Compose-observable state ──────────────────────────────────────────
    // Mirrors the iOS bridge's `@Published var eventCount: Int` so callers can
    // bind a "Captured: N events" indicator to actually-shipped events instead
    // of speculative frame counts. Reads from any thread are safe (Compose's
    // mutableStateOf is thread-safe for reads); writes happen on the writer
    // coroutine after each successful flush.
    private var _isConnected by mutableStateOf(false)
    /** True iff the TCP socket is open AND the writer loop is running. */
    public val isConnected: Boolean
        get() = _isConnected

    private var _eventsSent by mutableStateOf(0L)
    /**
     * Cumulative count of JSON-line events successfully written to the socket
     * (not just enqueued). Resets to 0 on a fresh [connect] call.
     */
    public val eventsSent: Long
        get() = _eventsSent

    // Listeners for sidecar control acknowledgments (e.g. save_now -> saved).
    // CopyOnWriteArrayList lets us iterate from the reader thread while
    // [requestSaveAndShare] mutates from any caller thread.
    private val ackListeners = CopyOnWriteArrayList<(ShareResult) -> Unit>()

    // Runtime kill-switch. When `false`, every `log*` call is a no-op and we
    // don't even build the JSON string — safe to wire unconditionally in
    // release builds and gate with `BuildConfig.DEBUG`.
    @Volatile private var enabled: Boolean = true

    private val minIntervalNanos: Long =
        if (rateHz <= 0) 0L else (1_000_000_000L / rateHz)

    /**
     * Open the TCP socket on a background thread and start the writer + reader loops.
     * Safe to call multiple times: no-op if already connected.
     *
     * The reader loop only exists to consume control acknowledgments from the
     * sidecar (e.g. the `saved` ack returned after [requestSaveAndShare]). It
     * is NOT a generic event router — non-control lines are silently dropped
     * because the sidecar has no reason to send them to us today.
     *
     * Each call installs a fresh event queue, so **events logged while the
     * bridge is disconnected are dropped, not replayed** on the next connect:
     * only what you log after `connect()` returns reaches the viewer. That is
     * deliberate — a reconnect should show live AR data, not one stale frame
     * from a session that ended minutes ago.
     */
    public fun connect() {
        if (writerJob?.isActive == true) return
        // Reset counters on every fresh connect so a flickering link doesn't
        // accumulate misleading totals across attempts.
        _eventsSent = 0L
        // Hand this connection its own outbox BEFORE the writer starts, so a
        // caller that enqueues the moment connect() returns cannot have its
        // event captured by the writer we are replacing (#2777).
        val box = Channel<String>(capacity = Channel.CONFLATED)
        outbox = box
        writerJob = scope.launch {
            // Capture local refs so the writer's finally block does NOT race a
            // subsequent connect() that may have replaced the writer/socket
            // fields. Without this, disconnect() → connect() → old writer's
            // finally would null out the NEW socket created by the new writer.
            var localSocket: Socket? = null
            var localWriter: BufferedWriter? = null
            var localReaderJob: Job? = null
            try {
                val s = Socket()
                s.connect(InetSocketAddress(host, port), /* timeout = */ 2000)
                val w = BufferedWriter(OutputStreamWriter(s.getOutputStream(), Charsets.UTF_8))
                localSocket = s
                localWriter = w
                socket = s
                writer = w
                _isConnected = true

                // Start the reader for sidecar acks AFTER the socket is live.
                localReaderJob = scope.launch { readSidecarAcks(s) }
                readerJob = localReaderJob

                // `box`, not the field: this writer only ever ships events
                // enqueued for ITS connection, so a cancellation that lands
                // late can no longer strand the next connection's first event.
                for (line in box) {
                    try {
                        w.write(line)
                        w.flush()
                        _eventsSent++
                    } catch (e: Exception) {
                        logWarning("write failed: ${e.message}")
                        break
                    }
                }
            } catch (e: Exception) {
                logWarning("connect to $host:$port failed: ${e.message}")
            } finally {
                _isConnected = false
                // This connection's outbox dies with it. Events enqueued while
                // no writer is running are dropped rather than buffered, so a
                // later connect() can't ship a stale event from a dead session.
                box.close()
                // Close ONLY the resources this writer owns, then null out the
                // shared fields ONLY if they still point to our locals (i.e. a
                // subsequent connect() hasn't already replaced them).
                try { localWriter?.close() } catch (_: Exception) {}
                try { localSocket?.close() } catch (_: Exception) {}
                if (writer === localWriter) writer = null
                if (socket === localSocket) socket = null
                localReaderJob?.cancel()
                if (readerJob === localReaderJob) readerJob = null
            }
        }
    }

    /**
     * Reads JSON-lines acks from the sidecar and dispatches each parsed
     * [RerunWireFormat.ControlAck] to subscribers. Blocking — runs on its
     * own coroutine. Exits when the socket closes or the scope is cancelled.
     */
    private fun readSidecarAcks(socket: Socket) {
        try {
            val reader = BufferedReader(InputStreamReader(socket.getInputStream(), Charsets.UTF_8))
            while (true) {
                val line = reader.readLine() ?: break
                if (line.isBlank()) continue
                val ack = RerunWireFormat.parseControlAck(line) ?: continue
                val result = ShareResult(
                    success = ack.success,
                    path = ack.path,
                    viewerUrl = ack.viewerUrl,
                    events = ack.events,
                    reason = ack.reason,
                )
                // Snapshot listeners; CopyOnWriteArrayList iteration is safe
                // even if a listener calls remove during dispatch.
                for (listener in ackListeners) {
                    try {
                        listener(result)
                    } catch (e: Exception) {
                        logWarning("ack listener threw: ${e.message}")
                    }
                }
            }
        } catch (e: Exception) {
            logVerbose("reader exit: ${e.message}")
        }
    }

    /**
     * Stop the writer loop and close the socket. Safe to call multiple times.
     * The bridge can be reused: call [connect] again to re-open.
     *
     * **Non-blocking.** The previous implementation called `runBlocking { job?.join() }`
     * to wait for the writer's `finally` block, which froze the calling thread
     * (typically Compose's main thread) until the socket finished closing — up
     * to several seconds on a flaky network. The new implementation cancels
     * the writer and lets the next [connect] guard against the race using a
     * fresh job: callers who need synchronous completion should use [closeAsync]
     * and `await()` the returned [Job].
     */
    public fun disconnect() {
        val job = writerJob
        writerJob = null
        // Flip the observable state up-front so callers see a deterministic
        // "disconnected" immediately after disconnect() returns. The writer's
        // own finally block also sets this, but it may run later on its IO
        // coroutine — and the public contract is that `isConnected == false`
        // the moment disconnect() / close() returns to the caller.
        _isConnected = false
        closeQuietly()
        job?.cancel()
        // No join() — caller's thread is not blocked. A subsequent connect()
        // creates a brand-new writer; the cancelled job's finally block runs
        // asynchronously on its original CoroutineScope.
    }

    /**
     * Like [disconnect], but returns the (already-cancelled) writer [Job] so
     * callers that need a strict happens-before relationship can `await()` /
     * `join()` it from a coroutine. Returns `null` if no writer was active.
     */
    public fun closeAsync(): Job? {
        val job = writerJob
        writerJob = null
        _isConnected = false
        closeQuietly()
        job?.cancel()
        return job
    }

    /** Release all resources. The bridge is unusable after this call. */
    public fun close() {
        disconnect()
        scope.cancel()
        outbox.close()
    }

    /**
     * Toggle the bridge at runtime. When `false`, every `log*` call is a
     * no-op and no JSON is built. Calling [connect]/[disconnect] is still
     * the right way to manage the socket — this only guards the hot path.
     */
    public fun setEnabled(enabled: Boolean) {
        this.enabled = enabled
    }

    // ── High-level convenience ────────────────────────────────────────────

    /**
     * Log everything useful about a single ARCore frame — camera pose,
     * currently tracked planes, and the point cloud. Honours the rate
     * limiter: the whole frame is either logged or dropped as one unit,
     * so you can't log half a frame.
     */
    public fun logFrame(session: Session, frame: Frame) {
        if (!enabled) return
        if (!shouldEmit(frame.timestamp)) return
        logCameraPose(frame.camera.pose, frame.timestamp)
        for (plane in frame.getUpdatedPlanes()) {
            if (plane.trackingState != TrackingState.TRACKING) continue
            enqueue(RerunWireFormat.plane(frame.timestamp, plane))
        }
        try {
            frame.acquirePointCloud().use { cloud ->
                enqueue(RerunWireFormat.pointCloud(frame.timestamp, cloud))
            }
        } catch (e: Exception) {
            // Point cloud acquisition can fail if the depth API isn't ready
            // — not a hard error, just drop the event for this frame.
            logVerbose("pointCloud skipped: ${e.message}")
        }
    }

    // ── Low-level per-event loggers ───────────────────────────────────────

    public fun logCameraPose(pose: Pose, timestampNanos: Long) {
        if (!enabled) return
        enqueue(RerunWireFormat.cameraPose(timestampNanos, pose))
    }

    public fun logPlanes(planes: Collection<Plane>, timestampNanos: Long) {
        if (!enabled) return
        for (plane in planes) {
            if (plane.trackingState != TrackingState.TRACKING) continue
            enqueue(RerunWireFormat.plane(timestampNanos, plane))
        }
    }

    public fun logPointCloud(cloud: com.google.ar.core.PointCloud, timestampNanos: Long) {
        if (!enabled) return
        enqueue(RerunWireFormat.pointCloud(timestampNanos, cloud))
    }

    public fun logAnchors(anchors: Collection<Anchor>, timestampNanos: Long) {
        if (!enabled) return
        for (anchor in anchors) enqueue(RerunWireFormat.anchor(timestampNanos, anchor))
    }

    public fun logHitResult(hit: HitResult, timestampNanos: Long) {
        if (!enabled) return
        enqueue(RerunWireFormat.hitResult(timestampNanos, hit))
    }

    /**
     * Log the cumulative camera trail as a single 3D polyline. Pass a
     * flat `[x0,y0,z0, x1,y1,z1, …]` buffer of accumulated camera
     * positions — keep it bounded (e.g. last 600 samples) so the JSON
     * line doesn't grow without bound over long sessions.
     *
     * The viewer at [`sceneview.github.io/rerun/`](https://sceneview.github.io/rerun/)
     * shows the trail under the camera entity, useful for spotting drift
     * or unusual operator motion patterns.
     */
    public fun logCameraTrail(
        positions: FloatArray,
        timestampNanos: Long,
        entity: String = "world/camera/trail",
    ) {
        if (!enabled) return
        if (positions.isEmpty()) return
        enqueue(RerunWireFormat.cameraTrailJson(timestampNanos, positions, entity))
    }

    /**
     * Log a scalar timeseries value (e.g. `tracking_quality`, feature-point
     * count, frame latency). The Rerun viewer renders it as a graph in the
     * timeline panel; the [entity] doubles as the legend label.
     *
     * Cheap enough to call every frame — let `rateHz` upstream throttle.
     */
    public fun logScalar(
        value: Float,
        entity: String,
        timestampNanos: Long,
    ) {
        if (!enabled) return
        enqueue(RerunWireFormat.scalarJson(timestampNanos, value, entity))
    }

    // ── Save & share ──────────────────────────────────────────────────────

    /**
     * Ask the Python sidecar to flush its in-memory recording to a `.rrd`
     * file on disk and reply with the path + the SceneView Rerun viewer URL.
     *
     * Requires the sidecar to be running with `--save` (the demo's
     * `rerun-bridge.py` defaults to live mode). If the sidecar is in live
     * mode, `callback` receives a [RerunWireFormat.ControlAck] with
     * `success = false` and a human-readable `reason`.
     *
     * The callback fires on the bridge's I/O thread — marshal to your UI
     * thread (e.g. via `mainHandler.post` or a Compose `LaunchedEffect`)
     * before touching UI state.
     *
     * Returns immediately. Does nothing if the bridge is not connected
     * (the control message would be dropped on the conflated outbox).
     */
    public fun requestSaveAndShare(callback: (ShareResult) -> Unit) {
        if (writerJob?.isActive != true) {
            callback(ShareResult(
                success = false,
                path = null,
                viewerUrl = null,
                events = 0,
                reason = "bridge not connected — call connect() first",
            ))
            return
        }
        // One-shot listener: fires once then unsubscribes itself.
        lateinit var listener: (ShareResult) -> Unit
        listener = { ack ->
            ackListeners.remove(listener)
            callback(ack)
        }
        ackListeners.add(listener)
        // Use a non-conflated path: `outbox` is conflated which would drop
        // pending event lines. Write directly to the writer instead.
        scope.launch {
            try {
                writer?.let {
                    it.write(RerunWireFormat.controlSaveNow())
                    it.flush()
                }
            } catch (e: Exception) {
                logWarning("control write failed: ${e.message}")
                ackListeners.remove(listener)
                callback(ShareResult(
                    success = false,
                    path = null,
                    viewerUrl = null,
                    events = 0,
                    reason = "control write failed: ${e.message}",
                ))
            }
        }
    }

    // ── Internals ─────────────────────────────────────────────────────────

    /**
     * Returns true if an event at the given device timestamp should be
     * emitted under the configured rate limiter. Must run on whatever
     * thread the caller is on — this is a hot-path check on the render
     * thread, so we use a volatile long and no locking.
     */
    private fun shouldEmit(timestampNanos: Long): Boolean {
        if (minIntervalNanos <= 0L) return true
        val delta = timestampNanos - lastEmitNanos
        if (delta < minIntervalNanos) return false
        lastEmitNanos = timestampNanos
        return true
    }

    /**
     * Enqueue a serialized JSON line for the writer loop. Non-blocking —
     * uses `trySend`, so if the channel already has a pending event the
     * new one overwrites it (conflated).
     */
    private fun enqueue(line: String) {
        outbox.trySend(line)
    }

    /** Log.w wrapper that swallows the "not mocked" error in unit tests. */
    private fun logWarning(msg: String) {
        try { Log.w(tag, msg) } catch (_: RuntimeException) { /* unit test stub */ }
    }

    /** Log.v wrapper that swallows the "not mocked" error in unit tests. */
    private fun logVerbose(msg: String) {
        try { Log.v(tag, msg) } catch (_: RuntimeException) { /* unit test stub */ }
    }

    private fun closeQuietly() {
        // Deliberately does NOT close the `outbox` FIELD. Only the writer owns
        // a channel, and it closes its own `box` local in its finally block.
        // Closing the field here would let a disconnect() racing a connect()
        // from another thread shut the freshly-installed channel out from
        // under the writer that just started — a connected-but-mute bridge.
        // The writer leaves its loop on the cancellation instead.
        try { writer?.close() } catch (_: Exception) {}
        try { socket?.close() } catch (_: Exception) {}
        writer = null
        socket = null
    }

    /**
     * Internal hook for unit tests: enqueue a pre-built JSON line directly,
     * bypassing the `enabled` flag and the rate limiter. Lets the socket
     * tests exercise the writer loop without needing a real ARCore [Pose].
     *
     * Do NOT call from production code — use the public `log*` methods.
     */
    internal fun testOnlyEnqueue(line: String) {
        outbox.trySend(line)
    }
}
