#!/usr/bin/env node
/**
 * Generate `src/generated/version.ts` from `package.json`.
 *
 * The generated module exposes `PACKAGE_VERSION` as a plain TypeScript
 * string constant baked at build time. This is what the MCP server
 * advertises to clients and what telemetry reports as `mcpVersion`.
 *
 * Bug history: pre-4.0.8 the version was hardcoded to "4.0.0" inside
 * `index.ts` and `telemetry.ts` and never bumped between releases. As a
 * result every install of every published version reported itself as
 * 4.0.0 to telemetry, making it impossible to measure adoption of new
 * releases. Wiring the version into the build pipeline closes that gap
 * — every `npm run build` snapshots the current `package.json` version
 * into the generated file.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const mcpRoot = resolve(__dirname, "..");

const pkgJson = JSON.parse(readFileSync(resolve(mcpRoot, "package.json"), "utf8"));
const version = pkgJson.version;

if (!version || typeof version !== "string") {
  console.error("[generate-version] FATAL: missing or invalid 'version' in package.json");
  process.exit(1);
}

const outDir = resolve(mcpRoot, "src/generated");
mkdirSync(outDir, { recursive: true });

const outPath = resolve(outDir, "version.ts");
const content =
  `// AUTO-GENERATED by scripts/generate-version.js — do not edit by hand.\n` +
  `// Snapshots the package.json "version" field at build time so that\n` +
  `// the MCP server and telemetry report the actual published version\n` +
  `// instead of a stale hardcoded constant.\n\n` +
  `export const PACKAGE_VERSION = "${version}" as const;\n`;

writeFileSync(outPath, content, "utf8");
// Log to stderr so we don't pollute stdout (npm pack --dry-run --json
// pipes stdout through, and the package-files test parses that JSON).
console.error(`[generate-version] wrote ${outPath} (version=${version})`);
