#!/usr/bin/env node
/**
 * Generate `src/generated/version.ts` from `package.json`.
 *
 * The generated module exposes `PACKAGE_VERSION` as a plain TypeScript
 * string constant baked at build time. This is what the MCP server
 * advertises to clients and what telemetry reports as `mcpVersion`.
 *
 * Bug history: pre-4.0.8 the version was hardcoded to "4.0.0" inside
 * `index.ts` and `telemetry.ts` and never bumped between releases. As a
 * result every install of every published version reported itself as
 * 4.0.0 to telemetry, making it impossible to measure adoption of new
 * releases. Wiring the version into the build pipeline closes that gap
 * — every `npm run build` snapshots the current `package.json` version
 * into the generated file.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const mcpRoot = resolve(__dirname, "..");

const pkgJson = JSON.parse(readFileSync(resolve(mcpRoot, "package.json"), "utf8"));
const version = pkgJson.version;

if (!version || typeof version !== "string") {
  console.error("[generate-version] FATAL: missing or invalid 'version' in package.json");
  process.exit(1);
}

// Also pull the SceneView SDK version from the root `gradle.properties`
// (the single source of truth declared in CLAUDE.md's Version Location
// Map). The MCP server advertises this when telling the user what artifact
// to add to their build — previously every tool body had `4.0.0`
// hardcoded so the LLM directed users to a 6-month-stale version. See
// #941.
const gradleProps = readFileSync(resolve(mcpRoot, "..", "gradle.properties"), "utf8");
const sdkMatch = gradleProps.match(/^\s*VERSION_NAME\s*=\s*([^\s#]+)/m);
if (!sdkMatch) {
  console.error("[generate-version] FATAL: VERSION_NAME not found in ../gradle.properties");
  process.exit(1);
}
const sdkVersion = sdkMatch[1].trim();

// The Flutter plugin is a SEPARATE track and must NOT reuse `sdkVersion`.
// `flutter_sceneview` is a caret range against pub.dev, so the version it
// names has to ALREADY EXIST on that registry; VERSION_NAME is the in-flight
// SDK version and routinely runs ahead of it. Pointing the generated setup
// guide at VERSION_NAME therefore emits a `pubspec.yaml` line that
// `flutter pub get` cannot resolve — measured on 2026-08-10, when this file
// generated `^4.26.0` while pub.dev's newest was 4.24.0. The same mistake had
// already been made (and fixed) in llms.txt; see the "lags pub.dev, not
// bumped" row in .claude/scripts/sync-versions.sh.
//
// Source of truth is the plugin's OWN README, which is the coordinate a human
// updates after a successful `flutter pub publish`. FATAL rather than falling
// back to sdkVersion: a silent fallback is exactly how the wrong version got
// shipped, and an MCP that emits an unresolvable dependency is worse than one
// that fails to build.
const flutterReadme = readFileSync(
  resolve(mcpRoot, "..", "flutter", "sceneview_flutter", "README.md"),
  "utf8"
);
const pubMatch = flutterReadme.match(
  /^\s*flutter_sceneview:\s*\^([0-9]+\.[0-9]+\.[0-9]+(?:-[a-zA-Z0-9.]+)?)/m
);
if (!pubMatch) {
  console.error(
    "[generate-version] FATAL: no `flutter_sceneview: ^X.Y.Z` line in " +
      "flutter/sceneview_flutter/README.md — that line is the published " +
      "pub.dev coordinate and must not be inferred from VERSION_NAME"
  );
  process.exit(1);
}
const flutterPubVersion = pubMatch[1];

const outDir = resolve(mcpRoot, "src/generated");
mkdirSync(outDir, { recursive: true });

const outPath = resolve(outDir, "version.ts");
const content =
  `// AUTO-GENERATED by scripts/generate-version.js — do not edit by hand.\n` +
  `// Snapshots both the MCP package version (from package.json) and the\n` +
  `// SceneView SDK version (from ../gradle.properties:VERSION_NAME) at\n` +
  `// build time so the MCP server, telemetry, and the install-snippet\n` +
  `// generators all report the actually-published versions instead of\n` +
  `// stale hardcoded constants. See #941.\n\n` +
  `export const PACKAGE_VERSION = "${version}" as const;\n` +
  `export const LATEST_SCENEVIEW_RELEASE = "${sdkVersion}" as const;\n` +
  `// The pub.dev coordinate for \`flutter_sceneview\`, read from the plugin's\n` +
  `// README. Deliberately NOT LATEST_SCENEVIEW_RELEASE: pub.dev lags the SDK,\n` +
  `// and a caret range against an unpublished version cannot be resolved.\n` +
  `export const LATEST_FLUTTER_PUB_RELEASE = "${flutterPubVersion}" as const;\n`;

writeFileSync(outPath, content, "utf8");
// Log to stderr so we don't pollute stdout (npm pack --dry-run --json
// pipes stdout through, and the package-files test parses that JSON).
console.error(
  `[generate-version] wrote ${outPath} ` +
    `(mcp=${version}, sdk=${sdkVersion}, flutter-pub=${flutterPubVersion})`
);

// Keep the `android-ok` test fixture's SceneView pin in sync with the SDK
// version we just snapshotted into `generated/version.ts`. The
// `analyze-project.test.ts` "up-to-date" assertion compares the analyzer's
// extracted version to LATEST_SCENEVIEW_VERSION; if the fixture drifts off
// gradle.properties (as it did between v4.1.1 and v4.1.2, see PR #1012),
// the test asserts `4.1.1 === 4.1.2` and fails the whole quality gate.
//
// The replacement is anchored on the gradle dependency syntax so we don't
// accidentally rewrite the unrelated `versionName "1.0"` line of the app
// fixture itself. A single `implementation("io.github.sceneview:sceneview:X.Y.Z")`
// is the only line we touch. The version pattern matches everything up to
// the closing quote OR single-quote OR closing paren (Groovy and Kotlin
// gradle DSLs are both covered), so pre-release suffixes like `-rc.1` or
// `-beta.2` round-trip correctly (an earlier `[\d.]+` regex truncated
// suffixes and left the previous tail behind on the revert path).
//
// IMPORTANT — only `android-ok/` is auto-synced. The sister fixtures
// `android-with-warnings/build.gradle.kts` (pinned at `2.2.1`) and
// `ios-outdated/Package.swift` (pinned at `3.0.0`) are *intentionally
// stale* — `analyze-project.test.ts` asserts `isOutdated === true` and
// the exact version against those values. Broadening the sync target
// would flip those tests to false-positive.
const fixturePath = resolve(
  mcpRoot,
  "src/__fixtures__/analyze-project/android-ok/build.gradle.kts"
);
try {
  const current = readFileSync(fixturePath, "utf8");
  const updated = current.replace(/(io\.github\.sceneview:sceneview:)[^"'\s)]+/, `$1${sdkVersion}`);
  if (updated !== current) {
    writeFileSync(fixturePath, updated, "utf8");
    console.error(`[generate-version] synced fixture ${fixturePath} -> sceneview:${sdkVersion}`);
  }
} catch (err) {
  // Non-fatal — the fixture is a test artefact, not a runtime dependency.
  // Log loudly so a CI failure can still surface what happened.
  console.error(`[generate-version] WARNING: could not sync fixture (${err.message})`);
}
