#!/usr/bin/env node
/**
 * Generate `src/generated/symbols.ts` from the committed binary-compatibility
 * `.api` dumps (issue #2760 — `validate_code` v2 symbol-existence check).
 *
 * Why the `.api` dumps and not Dokka: the dumps are already committed, always
 * in sync with the public API (the `apiCheck` Gradle task is a blocking CI
 * gate — quality gate #9), and parse in pure Node with zero Gradle in the
 * chain. That keeps `npm install` / `npm test` / `npm publish` self-contained
 * for the MCP package, exactly like the sibling `generate-llms-txt.js`.
 * Trade-off, stated honestly: JVM descriptors carry no Kotlin parameter
 * names, so this index answers "does this class/function/member exist?"
 * (the #1 AI failure mode), not "is this named argument right?". A future
 * Dokka-backed pass can add parameter names without changing consumers.
 *
 * Coverage = the Android/KMP surface (`sceneview`, `arsceneview`,
 * `sceneview-core`). Swift and Web have no committed dump and are NOT
 * indexed — the validator must scope symbol rules to Kotlin/Android code.
 *
 * Search order for each `<module>.api` (mirrors generate-llms-txt.js):
 *   1. SCENEVIEW_API_DUMPS env var (absolute path to a directory holding
 *      `<module>.api` files)
 *   2. ../<module>/api/<module>.api (repo root, canonical monorepo layout)
 *   3. ./api-dumps/<module>.api (local copies for a standalone build)
 *
 * The generated file is NOT committed (same "no committed generated
 * artefact" decision as #1928 for `llms-txt.ts`): it is regenerated by the
 * `prebuild`, `prepare` and `test` npm scripts, compiled by `tsc`, and the
 * published tarball ships only the compiled `dist/generated/symbols.js`.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const mcpRoot = resolve(__dirname, "..");

const MODULES = ["sceneview", "arsceneview", "sceneview-core"];

/** Locate `<module>.api`, or return null when the module can't be found. */
function locateDump(module) {
  const candidates = [
    process.env.SCENEVIEW_API_DUMPS && resolve(process.env.SCENEVIEW_API_DUMPS, `${module}.api`),
    resolve(mcpRoot, "..", module, "api", `${module}.api`),
    resolve(mcpRoot, "api-dumps", `${module}.api`),
  ].filter(Boolean);
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Classes that exist in the dump but are compiler artefacts, not API a user
 * can (or should) reference from Kotlin source.
 */
function isNoiseClass(binaryName) {
  return (
    binaryName.includes("ComposableSingletons$") ||
    binaryName.includes("$WhenMappings") ||
    binaryName.endsWith("$DefaultImpls") ||
    binaryName.endsWith("/BuildConfig") ||
    // Anonymous / local classes: a `$` segment starting with a digit.
    /\$\d/.test(binaryName)
  );
}

/** `getFoo`/`setFoo`/`isFoo` (JVM accessors) → the Kotlin property name. */
function propertyNameOf(funName) {
  let m = /^get([A-Z].*)$/.exec(funName);
  if (m) return m[1][0].toLowerCase() + m[1].slice(1);
  m = /^set([A-Z].*)$/.exec(funName);
  if (m) return m[1][0].toLowerCase() + m[1].slice(1);
  // Kotlin `isFoo` properties keep their name as-is.
  if (/^is[A-Z]/.test(funName)) return funName;
  return null;
}

/**
 * Parse one `.api` dump into { classes, topLevel }.
 *
 * Grammar (binary-compatibility-validator output — deliberately rigid):
 *   public [final |abstract ][interface ][annotation ]class a/b/C[$Inner] [: supers] {
 *   \tpublic [static ][final |abstract |synthetic ]fun name (desc)ret
 *   \tpublic [static ][final ][synthetic ]field name desc
 *   }
 */
function parseDump(text, module) {
  const classes = new Map(); // dotted FQCN -> { module, members: Set }
  const topLevel = new Map(); // function name -> Set(module)
  const facadePackages = new Set(); // packages that declare top-level functions

  let current = null; // { fqcn, isKtFacade, members }

  for (const rawLine of text.split("\n")) {
    const line = rawLine.trimEnd();

    const classMatch =
      /^public (?:final |abstract |open )?(?:interface )?(?:annotation )?class ([\w/$]+)/.exec(
        line
      );
    if (classMatch) {
      const binaryName = classMatch[1];
      if (isNoiseClass(binaryName)) {
        current = { skip: true };
        continue;
      }
      const dotted = binaryName.replaceAll("/", ".").replaceAll("$", ".");
      const isKtFacade = /Kt$/.test(binaryName.split("/").pop() || "");
      current = { fqcn: dotted, isKtFacade, members: new Set() };
      continue;
    }

    if (line === "}") {
      if (current && !current.skip) {
        if (current.isKtFacade) {
          // Top-level functions live in `<File>Kt` facades. Register the
          // function names globally; the facade class itself is not a type
          // a Kotlin user ever names. Its package IS importable, though —
          // record it so wildcard/package imports resolve even when the
          // package holds no plain class.
          facadePackages.add(current.fqcn.slice(0, current.fqcn.lastIndexOf(".")));
          for (const member of current.members) {
            if (!topLevel.has(member)) topLevel.set(member, new Set());
            topLevel.get(member).add(module);
          }
        } else {
          const prev = classes.get(current.fqcn);
          if (prev) {
            for (const m of current.members) prev.members.add(m);
          } else {
            classes.set(current.fqcn, {
              module,
              members: current.members,
            });
          }
        }
      }
      current = null;
      continue;
    }

    if (!current || current.skip) continue;

    // Members. Skip `synthetic` (accessors, $default bridges) — they are not
    // callable from Kotlin source under those names.
    const funMatch = /^\tpublic (?:static )?(?:final |abstract |open )?fun ([\w$<>]+) /.exec(line);
    if (funMatch) {
      if (/synthetic/.test(line)) continue;
      const name = funMatch[1];
      if (name === "<init>" || name === "<clinit>") continue;
      if (name.includes("$")) continue; // `foo$default`, `access$...`
      current.members.add(name);
      const prop = propertyNameOf(name);
      if (prop) current.members.add(prop);
      continue;
    }

    const fieldMatch = /^\tpublic (?:static )?(?:final )?field ([\w$]+) /.exec(line);
    if (fieldMatch) {
      if (/synthetic/.test(line)) continue;
      const name = fieldMatch[1];
      if (name === "$stable" || name.includes("$")) continue;
      current.members.add(name);
    }
  }

  return { classes, topLevel, facadePackages };
}

// ─── Read + parse every module ────────────────────────────────────────────────

const sources = [];
const allClasses = new Map();
const allTopLevel = new Map();
const allFacadePackages = new Set();
const missingModules = [];

for (const module of MODULES) {
  const path = locateDump(module);
  if (!path) {
    missingModules.push(module);
    continue;
  }
  sources.push(`${module}.api`);
  const { classes, topLevel, facadePackages } = parseDump(readFileSync(path, "utf-8"), module);
  for (const pkg of facadePackages) allFacadePackages.add(pkg);
  for (const [fqcn, entry] of classes) {
    const prev = allClasses.get(fqcn);
    if (prev) {
      for (const m of entry.members) prev.members.add(m);
    } else {
      allClasses.set(fqcn, entry);
    }
  }
  for (const [name, modules] of topLevel) {
    if (!allTopLevel.has(name)) allTopLevel.set(name, new Set());
    for (const m of modules) allTopLevel.get(name).add(m);
  }
}

if (missingModules.length === MODULES.length) {
  console.error(
    "[generate-symbols] could not locate any .api dump. Set SCENEVIEW_API_DUMPS, " +
      "build from the monorepo, or provide ./api-dumps/<module>.api copies."
  );
  process.exit(1);
}
if (missingModules.length > 0) {
  console.error(
    `[generate-symbols] WARNING: missing dumps for ${missingModules.join(", ")} — ` +
      "the index will be partial and unknown-symbol checks may under-report."
  );
}

// Fold Companion members into their host class: Kotlin call-sites write
// `ModelLoader.foo()`, never `ModelLoader.Companion.foo()`.
for (const [fqcn, entry] of [...allClasses]) {
  if (fqcn.endsWith(".Companion")) {
    const host = allClasses.get(fqcn.slice(0, -".Companion".length));
    if (host) {
      for (const m of entry.members) host.members.add(m);
      allClasses.delete(fqcn);
    }
  }
}

// ─── Emit ─────────────────────────────────────────────────────────────────────

const classesOut = {};
for (const fqcn of [...allClasses.keys()].sort()) {
  const { module, members } = allClasses.get(fqcn);
  classesOut[fqcn] = { module, members: [...members].sort() };
}
const topLevelOut = {};
for (const name of [...allTopLevel.keys()].sort()) {
  topLevelOut[name] = [...allTopLevel.get(name)].sort();
}

const packagesOut = [
  ...new Set([
    ...Object.keys(classesOut).map((fqcn) => fqcn.slice(0, fqcn.lastIndexOf("."))),
    ...allFacadePackages,
  ]),
].sort();

const index = {
  generatedFrom: sources,
  packages: packagesOut,
  classes: classesOut,
  topLevel: topLevelOut,
};

const outDir = resolve(mcpRoot, "src", "generated");
if (!existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
}
const outFile = resolve(outDir, "symbols.ts");

const header = [
  "// Auto-generated by scripts/generate-symbols.js — DO NOT EDIT BY HAND.",
  "//",
  "// Parsed from the committed binary-compatibility `.api` dumps (kept in",
  "// sync with the public API by the blocking `apiCheck` CI gate). Re-run",
  "// `node scripts/generate-symbols.js` (or `npm run build`) to refresh.",
  "",
  "/** Public-API symbol index for the Android/KMP SceneView surface. */",
  "export interface SymbolsIndex {",
  "  /** The `.api` dump files this index was generated from. */",
  "  generatedFrom: string[];",
  "  /** Every package that contains at least one public class. */",
  "  packages: string[];",
  "  /** Dotted FQCN → owning module + callable member/property names. */",
  "  classes: Record<string, { module: string; members: string[] }>;",
  "  /** Top-level function name → modules that declare it. */",
  "  topLevel: Record<string, string[]>;",
  "}",
  "",
].join("\n");

const body = `export const SYMBOLS: SymbolsIndex = ${JSON.stringify(index, null, 2)};\n`;

writeFileSync(outFile, `${header}\n${body}`);

// stderr only — a stdout banner interleaves with `npm pack --json` (#1113).
console.error(
  `[generate-symbols] wrote ${outFile} (${Object.keys(classesOut).length} classes, ` +
    `${Object.keys(topLevelOut).length} top-level functions from ${sources.join(", ")})`
);
