#!/usr/bin/env bash
#
# check-demo-class-refs.sh — flag stale demo-class / demo-id references in the
# hand-written AI-facing docs prose.
#
# WHY THIS EXISTS
# ---------------
# SceneView is an AI-first SDK: the prose docs (`llms.txt`, the agent skill
# `cheatsheet.md` / `recipes.md`, `docs/docs/recipes/*`, `samples/recipes/*`)
# are the product surface an AI reads to generate user code. When a demo is
# deleted or merged (the #2239 consolidation merged ~20 Android demos), only the
# COLLATOR-generated demos block in `llms.txt` is regenerated by
# `collate-demos.sh`. Hand-written prose OUTSIDE the markers — and every other
# doc — keeps naming the deleted Kotlin class (`AnimationDemo`, `MultiModelDemo`,
# `PhysicsDemo`) or the retired demo id (`sceneview://demo/gesture-editing`). An
# AI then confidently references a class / id that no longer exists. This whole
# class of drift slipped past CI and relied on a human reviewer each batch
# (#2316).
#
# WHAT IT CHECKS
# --------------
# Across the AI-facing prose surfaces it greps for:
#
#   1. A backtick-wrapped demo CLASS token `` `<Name>Demo` `` that is in NONE of
#      the live demo sets (Android Kotlin composables ∪ iOS Swift demo files ∪
#      web demo composables) — i.e. a demo deleted from every platform.
#
#   2. A `<Name>Demo.<ext>` FILE reference (`.kt` / `.swift` / `.ts`) whose
#      target file does not exist anywhere in the tree — a dead source link.
#
#   3. A retired demo ID referenced in deep-link form (`sceneview://demo/<id>`
#      or `demo/<id>`) that is no longer a live `ALL_DEMOS` id — caught from the
#      collator's per-demo bullet ids plus the router's retired-id alias table.
#
# WHAT IT DELIBERATELY DOES NOT FLAG (precision — this is an AI-facing guard, a
# false positive teaches a human to ignore it):
#   - The collator-generated demos block in `llms.txt` (between the BEGIN/END
#     markers) — it is regenerated and cannot drift.
#   - iOS `.swift` demo refs to files that EXIST (e.g. `AnimationDemo.swift`):
#     the iOS demo app legitimately keeps separate Animation / MultiModel /
#     Physics demos even though the Android ones were consolidated. Only a
#     `.swift` ref to a MISSING file is stale.
#   - Prose phrases that merely happen to contain a retired id as plain words
#     (e.g. "the gesture-editing API") — only the `demo/<id>` deep-link form is
#     a real id reference.
#
# ADVISORY-VS-BLOCKING (mirrors check-doc-drift.sh)
#   Default = advisory: prints findings, exit 0. `--fail` opts into a non-zero
#   exit. Wired into `ci.yml` → `repo-hygiene` as an advisory step alongside the
#   other doc gates. We FIX the known stale instances in the same change so the
#   default run is clean; the guard then catches the NEXT regression.
#
# USAGE
#   bash .claude/scripts/check-demo-class-refs.sh           # advisory, exit 0
#   bash .claude/scripts/check-demo-class-refs.sh --fail    # exit 1 on any finding
#   bash .claude/scripts/check-demo-class-refs.sh --list    # print the live sets + exit
#
# ROBUSTNESS CONTRACT (mirrors check-doc-drift.sh / impact-check.sh)
#   - Missing inputs [SKIP] rather than die under `set -euo pipefail`.
#   - Default exit code 0 (advisory); `--fail` opts into non-zero.
#   - Self-tested by test-check-demo-class-refs.sh (run in repo-hygiene first).

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

FAIL_ON_FINDING=false
LIST_ONLY=false
for arg in "$@"; do
    case "$arg" in
        --fail) FAIL_ON_FINDING=true ;;
        --list) LIST_ONLY=true ;;
        -h|--help) sed -n '2,60p' "$0"; exit 0 ;;
        *) printf "${RED}Unknown arg: %s${NC}\n" "$arg" >&2; exit 2 ;;
    esac
done

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

ANDROID_DEMOS_DIR="samples/android-demo/src/main/java/io/github/sceneview/demo/demos"
IOS_DEMOS_DIR="samples/ios-demo"
WEB_DEMOS_DIR="samples/web-demo"
FRAG_DIR="samples/android-demo/src/main/java/io/github/sceneview/demo/fragments"
ROUTER="samples/android-demo/src/main/java/io/github/sceneview/demo/DeepLinkRouter.kt"
LLMS_ROOT="llms.txt"
LLMS_BEGIN="<!-- BEGIN GENERATED DEMOS"
LLMS_END="<!-- END GENERATED DEMOS -->"

skip_note() { printf "${CYAN}ℹ SKIP${NC}  %s\n" "$1"; }

# ─── 1. Build the live demo-class allowlist ───────────────────────────────
# Union across every platform: a class that still exists ANYWHERE is not stale.
LIVE_CLASSES="$(mktemp)"
trap 'rm -f "$LIVE_CLASSES"' EXIT

# Android Kotlin: `fun <Name>Demo(` composables.
if [ -d "$ANDROID_DEMOS_DIR" ]; then
    grep -rhoE 'fun [A-Z][A-Za-z0-9]*Demo\b' "$ANDROID_DEMOS_DIR" 2>/dev/null \
        | sed -E 's/fun //' >> "$LIVE_CLASSES" || true
else
    skip_note "Android demos dir not checked out ($ANDROID_DEMOS_DIR) — Android classes not in allowlist."
fi

# iOS Swift: every `<Name>Demo.swift` file basename (the class == the file name).
if [ -d "$IOS_DEMOS_DIR" ]; then
    find "$IOS_DEMOS_DIR" -name '*Demo.swift' 2>/dev/null \
        | sed -E 's#.*/##; s/\.swift$//' >> "$LIVE_CLASSES" || true
else
    skip_note "iOS demos dir not checked out ($IOS_DEMOS_DIR) — iOS classes not in allowlist."
fi

# Web: `fun <Name>Demo(` composables (Kotlin/JS) if present.
if [ -d "$WEB_DEMOS_DIR" ]; then
    grep -rhoE 'fun [A-Z][A-Za-z0-9]*Demo\b' "$WEB_DEMOS_DIR" 2>/dev/null \
        | sed -E 's/fun //' >> "$LIVE_CLASSES" || true
fi

sort -u "$LIVE_CLASSES" -o "$LIVE_CLASSES"

# ─── 2. Build the live demo-id set + retired-id set ───────────────────────
# Live ids: the per-demo bullet ids the collator emits into llms.txt's generated
# block (single source of truth for ALL_DEMOS without running Gradle), with a
# fallback to scraping fragment `id = "<id>"` declarations.
LIVE_IDS="$(mktemp)"
RETIRED_IDS="$(mktemp)"
trap 'rm -f "$LIVE_CLASSES" "$LIVE_IDS" "$RETIRED_IDS"' EXIT

if [ -f "$LLMS_ROOT" ]; then
    awk -v b="$LLMS_BEGIN" -v e="$LLMS_END" '
        index($0,b){inside=1; next}
        index($0,e){inside=0; next}
        inside' "$LLMS_ROOT" \
        | grep -oE '^- `[a-z0-9][a-z0-9-]*`' 2>/dev/null \
        | sed -E 's/^- `//; s/`$//' >> "$LIVE_IDS" || true
fi
if [ ! -s "$LIVE_IDS" ] && [ -d "$FRAG_DIR" ]; then
    grep -rhoE 'id\s*=\s*"[a-z0-9][a-z0-9-]*"' "$FRAG_DIR" 2>/dev/null \
        | sed -E 's/.*"([^"]+)".*/\1/' >> "$LIVE_IDS" || true
fi
sort -u "$LIVE_IDS" -o "$LIVE_IDS"

# Retired ids: the keys of DeepLinkRouter.DEMO_ID_ALIASES — ids that no longer
# appear in ALL_DEMOS but used to. A deep-link to one is a stale id reference.
if [ -f "$ROUTER" ]; then
    awk '/val DEMO_ID_ALIASES/{a=1} a && /^[[:space:]]*\)/{a=0} a' "$ROUTER" \
        | grep -oE '"[a-z0-9][a-z0-9-]*"[[:space:]]+to' 2>/dev/null \
        | sed -E 's/^"([^"]+)".*/\1/' >> "$RETIRED_IDS" || true
fi
sort -u "$RETIRED_IDS" -o "$RETIRED_IDS"

if [ "$LIST_ONLY" = true ]; then
    printf "${CYAN}Live demo classes (%s):${NC}\n" "$(wc -l < "$LIVE_CLASSES" | tr -d ' ')"
    tr '\n' ' ' < "$LIVE_CLASSES"; echo
    printf "${CYAN}Live demo ids (%s):${NC}\n" "$(wc -l < "$LIVE_IDS" | tr -d ' ')"
    tr '\n' ' ' < "$LIVE_IDS"; echo
    printf "${CYAN}Retired demo ids (%s):${NC}\n" "$(wc -l < "$RETIRED_IDS" | tr -d ' ')"
    tr '\n' ' ' < "$RETIRED_IDS"; echo
    exit 0
fi

if [ ! -s "$LIVE_CLASSES" ] && [ ! -s "$LIVE_IDS" ]; then
    skip_note "No live demo classes or ids resolved (sparse clone?) — nothing to check against. PASS."
    exit 0
fi

# ─── 3. Assemble the prose surfaces to scan ───────────────────────────────
# Hand-written AI-facing docs. The collator-generated block in llms.txt is
# excised below (it is regenerated, cannot drift). The committed root README and
# other surfaces could be added later; the issue's surface is these four.
#
# DEMO_REF_FILES env override: a space/newline list of files to scan instead of
# the default discovery. The self-test injects a temp fixture this way so it
# never depends on the real doc tree.
PROSE_FILES=()
if [ -n "${DEMO_REF_FILES:-}" ]; then
    for f in $DEMO_REF_FILES; do [ -f "$f" ] && PROSE_FILES+=("$f"); done
else
    [ -f "$LLMS_ROOT" ] && PROSE_FILES+=("$LLMS_ROOT")
    for d in docs/docs/recipes samples/recipes; do
        [ -d "$d" ] && while IFS= read -r f; do PROSE_FILES+=("$f"); done \
            < <(find "$d" -name '*.md' 2>/dev/null)
    done
    # Android + web agent skills (NOT sceneview-ios: its recipes legitimately name
    # the live iOS Swift demos, already covered by the .swift-exists rule below).
    for d in agents/sceneview agents/sceneview-web; do
        [ -d "$d" ] && while IFS= read -r f; do PROSE_FILES+=("$f"); done \
            < <(find "$d" -name '*.md' 2>/dev/null)
    done
fi

if [ "${#PROSE_FILES[@]}" -eq 0 ]; then
    skip_note "No prose surfaces checked out — nothing to scan. PASS."
    exit 0
fi

FINDINGS=0
report() { # file line message
    printf "${YELLOW}⚠ STALE${NC} %s:%s\n        %s\n" "$1" "$2" "$3"
    FINDINGS=$((FINDINGS + 1))
}

# Strip the generated demos block from llms.txt so its bullets never count.
strip_generated() { # file -> stdout (with line numbers preserved via grep -n upstream)
    if [ "$1" = "$LLMS_ROOT" ]; then
        awk -v b="$LLMS_BEGIN" -v e="$LLMS_END" '
            index($0,b){inside=1; print ""; next}
            index($0,e){inside=0; print ""; next}
            inside{print ""; next}
            {print}' "$1"
    else
        cat "$1"
    fi
}

is_known_class() { grep -qxF "$1" "$LIVE_CLASSES"; }
is_live_id()     { grep -qxF "$1" "$LIVE_IDS"; }
is_retired_id()  { grep -qxF "$1" "$RETIRED_IDS"; }

for f in "${PROSE_FILES[@]}"; do
    [ -f "$f" ] || continue
    # Line-numbered, generated-block-stripped view.
    while IFS=: read -r lineno content; do
        [ -z "$content" ] && continue

        # (a) `<Name>Demo.<ext>` file references — flag if the file is missing.
        #     Catches a dead `.kt` / `.swift` / `.ts` source link. An existing
        #     iOS `.swift` demo is therefore NOT flagged.
        while read -r ref; do
            [ -z "$ref" ] && continue
            base="$(basename "$ref")"
            # Resolve: does any file with this basename exist in the tree?
            if ! git ls-files --error-unmatch "$ref" >/dev/null 2>&1 \
                && ! find samples -name "$base" -print -quit 2>/dev/null | grep -q .; then
                report "$f" "$lineno" "dead demo source reference '$base' — file not found in the tree"
            fi
        done < <(grep -oE '[A-Z][A-Za-z0-9]*Demo\.(kt|swift|ts)' <<<"$content" || true)

        # (b) backtick-wrapped `<Name>Demo` class tokens (no extension) — flag if
        #     the class exists on NO platform. A `.swift`/`.kt` suffix is handled
        #     in (a), so here we only see bare class tokens.
        while read -r tok; do
            [ -z "$tok" ] && continue
            cls="${tok//\`/}"
            if ! is_known_class "$cls"; then
                report "$f" "$lineno" "stale demo class '\`$cls\`' — not a live demo on any platform (deleted/renamed?)"
            fi
        done < <(grep -oE '`[A-Z][A-Za-z0-9]*Demo`' <<<"$content" || true)

        # (c) retired demo-id in the UNAMBIGUOUS deep-link form
        #     `sceneview://demo/<id>` — flag a retired id, or an id that is
        #     neither live nor a known retired alias. We anchor on the full
        #     `sceneview://demo/` scheme on purpose: a bare `demo/<x>` substring
        #     also matches source paths (`samples/android-demo/src/.../demo/...`)
        #     and would false-positive on every recipe that cites a file path.
        while read -r idref; do
            [ -z "$idref" ] && continue
            id="${idref#sceneview://demo/}"
            if is_retired_id "$id"; then
                report "$f" "$lineno" "retired demo id 'sceneview://demo/$id' — consolidated away; point at its live successor"
            elif ! is_live_id "$id"; then
                report "$f" "$lineno" "unknown demo id 'sceneview://demo/$id' — not in ALL_DEMOS and not a known retired alias"
            fi
        done < <(grep -oE 'sceneview://demo/[a-z0-9][a-z0-9-]*' <<<"$content" || true)

    done < <(strip_generated "$f" | grep -nE '.' || true)
done

echo
if [ "$FINDINGS" -eq 0 ]; then
    printf "${GREEN}✓ OK${NC}   No stale demo-class / demo-id references in %s AI-facing prose file(s).\n" "${#PROSE_FILES[@]}"
    exit 0
fi

printf "${RED}✗ %s stale demo reference(s) found.${NC}\n" "$FINDINGS"
printf "Fix: point each at a LIVE demo class/id. A demo merged in #2239 lives under its\n"
printf "consolidated successor (e.g. AnimationDemo+PhysicsDemo → AnimationPhysicsDemo,\n"
printf "MultiModelDemo → ModelViewerDemo). Run with --list to see the live sets.\n"

if [ "$FAIL_ON_FINDING" = true ]; then
    exit 1
fi
# Advisory by default (mirrors check-doc-drift.sh): surface, don't block.
printf "${YELLOW}(advisory — not failing the build; pass --fail to gate)${NC}\n"
exit 0
