#!/usr/bin/env bash
#
# check-llms-drift.sh — block PRs that introduce llms.txt mirror drift.
#
# `llms.txt` (root) is the single source of truth for the SceneView API
# reference that LLMs and MCP servers consume. Two checked-in mirrors must
# stay byte-identical to it:
#
#   1. `docs/docs/llms.txt` — served by mkdocs (issue #899).
#   2. `mcp/src/generated/llms-txt.ts` — the embedded bundle shipped to the
#      Cloudflare-Workers MCP gateway and the npm `sceneview-mcp` package,
#      regenerated by `mcp/scripts/generate-llms-txt.js` (issue #1808).
#
# PR #1815 wired both drift detectors into `sync-versions.sh`. But
# `sync-versions.sh` is NOT invoked by `quality-gate.sh` (the PR-blocking CI
# gate), so PR #1822 was able to land `DepthHitResultNode` docs in root
# `llms.txt` without updating either mirror — the drift sat on `main` for 2
# commits until #1817 healed it (#1847).
#
# This script extracts the two drift checks into a focused, fast helper that
# the quality gate can call directly. It only reports drift (no `--fix`); use
# `bash .claude/scripts/sync-versions.sh --fix` to regenerate the mirrors.
#
# Usage:
#   bash .claude/scripts/check-llms-drift.sh
#
# Exit code: 0 if all mirrors are in sync, 1 if any mirror has drifted.
#
# Closes #1847.

set -u

ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
if [ -z "$ROOT" ]; then
    echo "check-llms-drift.sh: not inside a git checkout" >&2
    exit 2
fi

LLMS="$ROOT/llms.txt"
DOCS_LLMS="$ROOT/docs/docs/llms.txt"
MCP_BUNDLE="$ROOT/mcp/src/generated/llms-txt.ts"
MCP_GEN_SCRIPT="$ROOT/mcp/scripts/generate-llms-txt.js"

ERRORS=0

# Colors (only when stdout is a TTY).
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    NC='\033[0m'
else
    RED=''
    GREEN=''
    NC=''
fi

# ─── 1. docs/docs/llms.txt mirror (issue #899) ─────────────────────────
if [ ! -f "$LLMS" ]; then
    echo "check-llms-drift.sh: root llms.txt missing — nothing to check" >&2
    exit 0
fi

if [ -f "$DOCS_LLMS" ]; then
    if ! diff -q "$LLMS" "$DOCS_LLMS" >/dev/null 2>&1; then
        echo -e "${RED}MISMATCH: docs/docs/llms.txt has drifted from root llms.txt${NC}"
        echo "  Run: bash .claude/scripts/sync-versions.sh --fix"
        echo "  Diff (first 5 hunks):"
        # `head -N` closes the pipe early; suppress SIGPIPE so the script keeps
        # running the MCP bundle check below.
        { diff -u "$LLMS" "$DOCS_LLMS" 2>&1 || true; } | head -25 | sed 's/^/    /'
        ERRORS=$((ERRORS + 1))
    fi
fi

# ─── 2. mcp/src/generated/llms-txt.ts bundle (issue #1808) ─────────────
# Rebuild the expected bundle into a temp file and compare — no destructive
# write. The bundle ends with `;\n` so we use a real file (not `$(...)`) to
# avoid bash stripping the trailing newline.
if [ -f "$MCP_BUNDLE" ] && [ -f "$MCP_GEN_SCRIPT" ] && command -v node >/dev/null 2>&1; then
    EXPECTED_BUNDLE_FILE=$(mktemp -t sv-llms-txt.XXXXXX 2>/dev/null) || EXPECTED_BUNDLE_FILE=""
    if [ -n "$EXPECTED_BUNDLE_FILE" ]; then
        if node -e '
            const { readFileSync, writeFileSync } = require("node:fs");
            const [src, dst] = process.argv.slice(1);
            const content = readFileSync(src, "utf-8");
            const header = [
              "// Auto-generated by scripts/generate-llms-txt.js — DO NOT EDIT BY HAND.",
              "//",
              "// Re-run `node scripts/generate-llms-txt.js` (or `npm run build`) after",
              "// editing the root `llms.txt` to refresh this file.",
              "",
              "/** The full SceneView LLMs API reference, embedded as a string constant. */",
            ].join("\n");
            writeFileSync(dst, header + "\n" + "export const LLMS_TXT = " + JSON.stringify(content) + ";\n");
        ' "$LLMS" "$EXPECTED_BUNDLE_FILE" 2>/dev/null; then
            if ! diff -q "$EXPECTED_BUNDLE_FILE" "$MCP_BUNDLE" >/dev/null 2>&1; then
                echo -e "${RED}MISMATCH: mcp/src/generated/llms-txt.ts is out of sync with root llms.txt${NC}"
                echo "  Run: cd mcp && node scripts/generate-llms-txt.js"
                ERRORS=$((ERRORS + 1))
            fi
        fi
        rm -f "$EXPECTED_BUNDLE_FILE"
    fi
fi

if [ "$ERRORS" -eq 0 ]; then
    echo -e "${GREEN}llms.txt mirrors in sync${NC}"
    exit 0
else
    exit 1
fi
