#!/usr/bin/env bash
# collate-demos.sh — Regenerate GeneratedDemos.kt from the per-demo
# fragments under `src/main/java/io/github/sceneview/demo/fragments/`.
#
# Each fragment file declares ONE `object <Id>Fragment : DemoFragment { ... }`.
# This script discovers every such fragment and emits a single
# `GeneratedDemos.kt` that aggregates them into:
#
#   - `GeneratedDemos.all: List<DemoEntry>` — drives the central registry
#     (`ALL_DEMOS`) and the demo grid in `DemoListScreen`.
#   - `GeneratedDemos.route(id, onBack)` — drives the deep-link router
#     (`DemoRouter`); returns a composable lambda or null.
#
# Fragments are sorted by demo id for a stable, conflict-free diff so two
# parallel PRs adding two different demos never collide on this file.
#
# Idempotent: running this script twice produces a byte-identical file.
#
# Usage:
#   bash samples/android-demo/scripts/collate-demos.sh           # write
#   bash samples/android-demo/scripts/collate-demos.sh --check   # exit non-zero
#                                                                # if file is stale

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$REPO_ROOT"

FRAG_DIR="samples/android-demo/src/main/java/io/github/sceneview/demo/fragments"
OUT_FILE="$FRAG_DIR/GeneratedDemos.kt"

CHECK_MODE=false
case "${1:-}" in
    --check) CHECK_MODE=true ;;
    "") ;;
    *) echo "Usage: $0 [--check]" >&2; exit 1 ;;
esac

[ -d "$FRAG_DIR" ] || { echo "Error: $FRAG_DIR not found." >&2; exit 1; }

# Discover all fragment object declarations. Each fragment file declares
# exactly one `object <Name>Fragment : DemoFragment`. We extract `<Name>Fragment`
# and the demo id from `id = "<id>"`. We pair them, sort by demo id, and
# emit the generated file.
#
# We skip:
#   - DemoFragment.kt (the interface itself)
#   - GeneratedDemos.kt (the output of this script)
TMP_PAIRS="$(mktemp)"
trap 'rm -f "$TMP_PAIRS"' EXIT

shopt -s nullglob
fragment_count=0
for f in "$FRAG_DIR"/*Fragment.kt; do
    base="$(basename "$f")"
    [ "$base" = "DemoFragment.kt" ] && continue
    # Extract the object name (the symbol that implements DemoFragment).
    obj_name=$(grep -oE '^object [A-Za-z0-9_]+Fragment\b' "$f" | head -n1 | awk '{print $2}' || true)
    if [ -z "$obj_name" ]; then
        echo "Error: $f does not declare a top-level 'object <Name>Fragment : DemoFragment'." >&2
        exit 1
    fi
    # Extract the demo id from `id = "<id>"`.
    demo_id=$(grep -oE 'id\s*=\s*"[^"]+"' "$f" | head -n1 | sed -E 's/.*"([^"]+)".*/\1/')
    if [ -z "$demo_id" ]; then
        echo "Error: $f does not declare 'id = \"<demo-id>\"' on its DemoEntry." >&2
        exit 1
    fi
    # Sanity check: the fragment file is named <CamelCase(id)>Fragment.kt.
    # Not enforced strictly here (would reject legitimate hand-renames) but
    # the CamelCase mapping is the recommended convention.
    printf '%s\t%s\n' "$demo_id" "$obj_name" >> "$TMP_PAIRS"
    fragment_count=$((fragment_count + 1))
done

if [ "$fragment_count" -eq 0 ]; then
    echo "Error: no *Fragment.kt files found under $FRAG_DIR (other than DemoFragment.kt)." >&2
    exit 1
fi

# Detect duplicate ids — two fragments registering the same demo id would
# silently shadow each other in the router.
DUPES=$(cut -f1 "$TMP_PAIRS" | sort | uniq -d)
if [ -n "$DUPES" ]; then
    echo "Error: duplicate demo ids:" >&2
    echo "$DUPES" >&2
    exit 1
fi

# Sort by demo id (column 1) for a stable diff.
SORTED_PAIRS="$(mktemp)"
trap 'rm -f "$TMP_PAIRS" "$SORTED_PAIRS"' EXIT
sort -k1,1 "$TMP_PAIRS" > "$SORTED_PAIRS"

# Emit GeneratedDemos.kt.
NEW_FILE="$(mktemp)"
trap 'rm -f "$TMP_PAIRS" "$SORTED_PAIRS" "$NEW_FILE"' EXIT

{
    cat <<'HEADER'
// AUTO-GENERATED by samples/android-demo/scripts/collate-demos.sh — DO NOT EDIT.
//
// This file is regenerated from every `*Fragment.kt` under
// `src/main/java/io/github/sceneview/demo/fragments/`. To add or remove a demo,
// add or remove a fragment file and re-run the collator; never edit this file
// by hand.
//
// Fragments are sorted by demo id so two parallel PRs adding two different
// demos never collide on this file (issue #1797).
package io.github.sceneview.demo.fragments

import androidx.compose.runtime.Composable
import io.github.sceneview.demo.DemoEntry

/**
 * Generated aggregate of every [DemoFragment] declared under
 * `io.github.sceneview.demo.fragments`. Drives [io.github.sceneview.demo.ALL_DEMOS]
 * and [io.github.sceneview.demo.DemoRouter]. Regenerate with
 * `samples/android-demo/scripts/collate-demos.sh`.
 */
object GeneratedDemos {
    /** All fragments, sorted by demo id. */
    val fragments: List<DemoFragment> = listOf(
HEADER

    # Emit list entries, sorted by id.
    while IFS=$'\t' read -r _id obj; do
        printf '        %s,\n' "$obj"
    done < "$SORTED_PAIRS"

    cat <<'MIDDLE'
    )

    /** Convenience: every demo's metadata, in the same order as [fragments]. */
    val all: List<DemoEntry> = fragments.map { it.entry }

    /**
     * Returns the composable for the demo with the given [id], or `null` if no
     * fragment registers that id. The caller (typically
     * [io.github.sceneview.demo.DemoRouter]) is expected to handle the null
     * case by falling back to a placeholder screen.
     */
    @Composable
    fun Screen(id: String, onBack: () -> Unit): Boolean {
        when (id) {
MIDDLE

    # Emit the `when` branches, also sorted by id for diff stability.
    while IFS=$'\t' read -r demo_id obj; do
        printf '            "%s" -> %s.Screen(onBack)\n' "$demo_id" "$obj"
    done < "$SORTED_PAIRS"

    cat <<'FOOTER'
            else -> return false
        }
        return true
    }
}
FOOTER
} > "$NEW_FILE"

if [ "$CHECK_MODE" = true ]; then
    if [ ! -f "$OUT_FILE" ] || ! cmp -s "$NEW_FILE" "$OUT_FILE"; then
        echo "Error: $OUT_FILE is out of date. Run 'bash samples/android-demo/scripts/collate-demos.sh'." >&2
        if [ -f "$OUT_FILE" ]; then
            diff -u "$OUT_FILE" "$NEW_FILE" || true
        fi
        exit 1
    fi
    echo "OK: $OUT_FILE is in sync with $fragment_count fragment(s)."
    exit 0
fi

mv "$NEW_FILE" "$OUT_FILE"
echo "Regenerated $OUT_FILE from $fragment_count fragment(s)."
