/**
 * generate_world — World Labs (Marble) BYOK text/image/video→3D-world tool.
 *
 * `generate_3d_model` makes one object; this tool makes the *room around it*:
 * a navigable 3D Gaussian-splat world generated by World Labs' Marble model
 * from a text prompt, a single image (optionally a 360° panorama) or a short
 * video clip, via the World API (api.worldlabs.ai). The result is a set of
 * asset URLs — `.spz` splats in three resolutions, a collider mesh (GLB) and an
 * equirectangular panorama (PNG) — which SceneView loads with `SplatNode`
 * (Android), `addSplatNode(url)` (web) and the ordinary model / image loaders.
 *
 * The tool is BYOK — users bring their own `WORLDLABS_API_KEY` (create one at
 * platform.worldlabs.ai; API credits are bought there and are SEPARATE from
 * the Marble consumer app's credits). We never ship or proxy a key, so there is
 * no server-side key custody and no cost to us — the `TRIPO_API_KEY` pattern
 * of `generate_3d_model`. Because a single call can spend up to ~3000 credits
 * (~$2.40) of the caller's money and relays caller-supplied media URLs, the
 * tool is served by the local stdio package only (see `surfaces.ts`).
 *
 * API contract (World API, reconstructed September 2026 from the official SDK
 * wrappers and the docs.worldlabs.ai quickstart — re-verify field names against
 * https://docs.worldlabs.ai/api before extending):
 *   1. POST https://api.worldlabs.ai/marble/v1/worlds:generate
 *      WLT-Api-Key: <key>
 *      {
 *        "display_name": "...",
 *        "model": "marble-1.0-draft" | "marble-1.1" | "marble-1.1-plus",
 *        "world_prompt": {
 *          "type": "text" | "image" | "video",
 *          "text_prompt": "...",                                    // text, or a guide for media
 *          "image_prompt": { "source": "uri", "uri": "https://...", "is_pano": true },
 *          "video_prompt": { "source": "uri", "uri": "https://..." }
 *        },
 *        "seed": 42
 *      }
 *      → a long-running operation: { "operation_id" | "name": "operations/<id>", "done": false }
 *   2. GET https://api.worldlabs.ai/marble/v1/operations/{id} — poll until
 *      `done` is true. Google-style LRO: failure is `error` being present on a
 *      done operation, success is `response` carrying the world. Progress
 *      lives in `metadata.progress.{status,description}`.
 *      On success, `response.assets` carries `splats.spz_urls.{100k,500k,full_res}`,
 *      `mesh.collider_mesh_url`, `imagery.pano_url`, `thumbnail_url` and `caption`.
 *
 * Costs (docs.worldlabs.ai/api/pricing, September 2026): $1 buys 1250 credits;
 * a draft world is 150–250 credits (~$0.12–0.20, well under a minute), a
 * marble-1.1 world 1500 (~$1.20, 1–5 min), a marble-1.1-plus world 1500–3000
 * (~$1.20–2.40). Credits never expire; `GET /marble/v1/credits` reads the balance.
 *
 * All network errors, missing keys, operation failures and poll timeouts are
 * translated to a structured `GenerateWorldError` so the MCP handler can
 * render a clear message without crashing the server. The API key never
 * appears in any message, log line or result.
 */

// ─── Configuration ──────────────────────────────────────────────────────────

const WORLDLABS_BASE_URL = "https://api.worldlabs.ai/marble/v1";
const GENERATE_ENDPOINT = `${WORLDLABS_BASE_URL}/worlds:generate`;
const OPERATIONS_ENDPOINT = `${WORLDLABS_BASE_URL}/operations`;
const PLATFORM_URL = "https://platform.worldlabs.ai";
const API_KEY_ENV = "WORLDLABS_API_KEY";
/** Header World Labs authenticates with (not `Authorization`). */
const API_KEY_HEADER = "WLT-Api-Key";
/** Conservative cap — World Labs documents no hard limit; long prompts add nothing. */
const MAX_PROMPT_LENGTH = 2000;
/** Longest `display_name` we derive from a prompt. */
const MAX_DISPLAY_NAME_LENGTH = 60;

/** How often to re-poll the operation while it is running. */
const DEFAULT_POLL_INTERVAL_MS = 3_000;

/**
 * Quality tiers. Deadlines are generous because a full Marble world takes
 * ~5 minutes under normal load; a timeout still hands back the operation id
 * so the caller can resume polling with `operationId` instead of paying twice.
 */
const QUALITY_TIERS = {
  draft: {
    model: "marble-1.0-draft",
    label: "draft (marble-1.0-draft — fast preview, 150–250 credits ≈ $0.12–0.20)",
    credits: "150–250",
    timeoutMs: 180_000,
  },
  standard: {
    model: "marble-1.1",
    label: "standard (marble-1.1 — full-quality world, 1500 credits ≈ $1.20, 1–5 min)",
    credits: "1500",
    timeoutMs: 540_000,
  },
  large: {
    model: "marble-1.1-plus",
    label: "large (marble-1.1-plus — bigger, auto-expanded world, 1500–3000 credits ≈ $1.20–2.40)",
    credits: "1500–3000",
    timeoutMs: 720_000,
  },
} as const;

const LICENSE_NOTE =
  "Generated with your own World Labs API key — usage rights follow your World Labs plan's terms (https://platform.worldlabs.ai). Check those terms before redistributing a generated world in a published app.";

const ATTRIBUTION = "World Labs Marble (https://www.worldlabs.ai)";

// ─── Public types ───────────────────────────────────────────────────────────

export type WorldQuality = keyof typeof QUALITY_TIERS;

export interface GenerateWorldOptions {
  /**
   * Text description of the world. Alone → text→world. Together with
   * `imageUrl` / `videoUrl` it guides the media-based generation.
   */
  prompt?: string;
  /** Public HTTPS URL of a source image (JPEG/PNG/WebP). Exclusive with `videoUrl`. */
  imageUrl?: string;
  /** Treat `imageUrl` as a 360° equirectangular panorama. */
  isPanorama?: boolean;
  /** Public HTTPS URL of a source video (mp4/mov/webm, ≤30 s, ≤100 MB). Exclusive with `imageUrl`. */
  videoUrl?: string;
  /**
   * Quality tier. `"draft"` (default) = marble-1.0-draft, cheap and fast.
   * `"standard"` = marble-1.1. `"large"` = marble-1.1-plus.
   */
  quality?: WorldQuality;
  /** Optional seed for reproducible generations. */
  seed?: number;
  /**
   * Resume polling an operation returned by an earlier call that timed out.
   * Exclusive with every input above — nothing new is generated or billed.
   */
  operationId?: string;
  /** Test/tuning hook — poll cadence. Not exposed in the MCP schema. */
  pollIntervalMs?: number;
  /** Test/tuning hook — overall deadline. Not exposed in the MCP schema. */
  timeoutMs?: number;
}

export interface WorldSplatUrls {
  /** ~100k splats — the tier to load on phones. */
  k100: string | null;
  /** ~500k splats — desktop / web quality. */
  k500: string | null;
  /** ~2M splats — the full export. */
  full: string | null;
}

export interface GeneratedWorld {
  operationId: string;
  worldId: string | null;
  displayName: string;
  /** Marble model id that produced the world, e.g. `marble-1.1`. */
  model: string;
  /** Quality tier the call asked for, or `null` when resuming an operation. */
  quality: WorldQuality | null;
  mode: "text" | "image" | "video" | "resumed";
  /** Echo of the prompt / media URL that produced the world (or the operation id). */
  input: string;
  caption: string | null;
  splatUrls: WorldSplatUrls;
  colliderMeshUrl: string | null;
  panoramaUrl: string | null;
  thumbnailUrl: string | null;
  /** Credits the tier is billed at, from the public price list — not read from the API. */
  estimatedCredits: string | null;
  license: string;
  attribution: string;
}

export interface GenerateWorldSuccess {
  ok: true;
  world: GeneratedWorld;
}

export type GenerateWorldErrorCode =
  | "missing_key"
  | "unauthorized"
  | "payment_required"
  | "rate_limited"
  | "network"
  | "bad_response"
  | "invalid_input"
  | "task_failed"
  | "timeout";

export interface GenerateWorldError {
  ok: false;
  code: GenerateWorldErrorCode;
  message: string;
  /** Set when an operation exists, so the caller can resume with `operationId`. */
  operationId?: string;
}

export type GenerateWorldResult = GenerateWorldSuccess | GenerateWorldError;

// ─── World API response shapes (only the fields we actually read) ───────────

interface WorldLabsErrorBody {
  error?: { message?: string; code?: string | number } | string;
  detail?: string;
  message?: string;
}

interface WorldLabsOperation {
  operation_id?: string;
  name?: string;
  done?: boolean;
  error?: { message?: string; code?: string | number } | string;
  metadata?: { progress?: { status?: string; description?: string } };
  response?: WorldLabsWorld;
}

interface WorldLabsWorld {
  id?: string;
  world_id?: string;
  display_name?: string;
  generation_input?: { model?: string };
  assets?: {
    splats?: { spz_urls?: Record<string, string | undefined> };
    mesh?: { collider_mesh_url?: string };
    imagery?: { pano_url?: string };
    thumbnail_url?: string;
    caption?: string;
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function missingKeyError(): GenerateWorldError {
  return {
    ok: false,
    code: "missing_key",
    message: [
      `generate_world needs a World Labs API key (BYOK — generations are billed to YOUR World Labs account, nothing is charged by SceneView).`,
      "",
      `1. Create an API key and buy API credits at ${PLATFORM_URL} ($1 = 1250 credits; a draft world is 150–250 credits). API credits are separate from the Marble app's credits.`,
      `2. Set the ${API_KEY_ENV} environment variable in your MCP client config:`,
      "",
      "   Claude Desktop / Cursor / Windsurf:",
      "   {",
      '     "mcpServers": {',
      '       "sceneview": {',
      '         "command": "npx",',
      '         "args": ["-y", "sceneview-mcp"],',
      `         "env": { "${API_KEY_ENV}": "YOUR_KEY_HERE" }`,
      "       }",
      "     }",
      "   }",
    ].join("\n"),
  };
}

/** World Labs fetches the media itself, so only a public https URL will do. */
function isHttpsUrl(value: string): boolean {
  return /^https:\/\/\S+$/i.test(value.trim());
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function apiMessage(body: unknown): string | undefined {
  if (!body || typeof body !== "object") return undefined;
  const b = body as WorldLabsErrorBody;
  if (typeof b.error === "string") return b.error;
  if (b.error && typeof b.error === "object" && typeof b.error.message === "string") {
    return b.error.message;
  }
  if (typeof b.detail === "string") return b.detail;
  if (typeof b.message === "string") return b.message;
  return undefined;
}

/** Map a non-OK World API HTTP response to a structured error. */
function httpError(status: number, statusText: string, detail?: string): GenerateWorldError {
  const suffix = detail ? ` (${detail})` : "";
  if (status === 401 || status === 403) {
    return {
      ok: false,
      code: "unauthorized",
      message: `World Labs rejected the API key (HTTP ${status})${suffix}. Double-check the key at ${PLATFORM_URL}, or create a new one.`,
    };
  }
  if (status === 402) {
    return {
      ok: false,
      code: "payment_required",
      message: `World Labs answered 402 Payment Required${suffix}. Your API credit balance is too low for this tier. IMPORTANT: credits bought in the Marble app (marble.worldlabs.ai) are SEPARATE from API Platform credits — top up at ${PLATFORM_URL}, or retry with quality "draft" (150–250 credits).`,
    };
  }
  if (status === 429) {
    return {
      ok: false,
      code: "rate_limited",
      message: `World Labs rate limit reached (HTTP 429)${suffix}. Wait a minute and retry, or check your plan's limits at ${PLATFORM_URL}.`,
    };
  }
  return {
    ok: false,
    code: "bad_response",
    message: `World Labs returned HTTP ${status} ${statusText || ""}${suffix}`.trim(),
  };
}

function operationIdOf(op: WorldLabsOperation): string | undefined {
  if (typeof op.operation_id === "string" && op.operation_id.length > 0) return op.operation_id;
  if (typeof op.name === "string" && op.name.length > 0) {
    const tail = op.name.split("/").pop();
    if (tail && tail.length > 0) return tail;
  }
  return undefined;
}

function displayNameFor(prompt: string | undefined, mode: "text" | "image" | "video"): string {
  if (prompt && prompt.length > 0) {
    const oneLine = prompt.replace(/\s+/g, " ").trim();
    return oneLine.length > MAX_DISPLAY_NAME_LENGTH
      ? `${oneLine.slice(0, MAX_DISPLAY_NAME_LENGTH - 1)}…`
      : oneLine;
  }
  return mode === "video" ? "SceneView world (from video)" : "SceneView world (from image)";
}

/**
 * Build the `worlds:generate` request body for the requested mode + tier.
 * Exported for tests only.
 */
export function buildGenerateBody(options: {
  prompt?: string;
  imageUrl?: string;
  isPanorama?: boolean;
  videoUrl?: string;
  quality: WorldQuality;
  seed?: number;
}): Record<string, unknown> {
  const tier = QUALITY_TIERS[options.quality];
  const mode: "text" | "image" | "video" = options.videoUrl
    ? "video"
    : options.imageUrl
      ? "image"
      : "text";

  const worldPrompt: Record<string, unknown> = { type: mode };
  if (options.prompt !== undefined && options.prompt.length > 0) {
    worldPrompt.text_prompt = options.prompt;
  }
  if (mode === "image") {
    const imagePrompt: Record<string, unknown> = { source: "uri", uri: options.imageUrl };
    if (options.isPanorama) imagePrompt.is_pano = true;
    worldPrompt.image_prompt = imagePrompt;
  } else if (mode === "video") {
    worldPrompt.video_prompt = { source: "uri", uri: options.videoUrl };
  }

  const body: Record<string, unknown> = {
    display_name: displayNameFor(options.prompt, mode),
    model: tier.model,
    world_prompt: worldPrompt,
  };
  if (typeof options.seed === "number" && Number.isFinite(options.seed)) {
    body.seed = Math.trunc(options.seed);
  }
  return body;
}

function extractWorld(
  world: WorldLabsWorld,
  meta: {
    operationId: string;
    quality: WorldQuality | null;
    mode: GeneratedWorld["mode"];
    input: string;
    fallbackModel: string;
  }
): GeneratedWorld | GenerateWorldError {
  const assets = world.assets ?? {};
  const spz = assets.splats?.spz_urls ?? {};
  const splatUrls: WorldSplatUrls = {
    k100: spz["100k"] ?? null,
    k500: spz["500k"] ?? null,
    full: spz.full_res ?? null,
  };
  const colliderMeshUrl = assets.mesh?.collider_mesh_url ?? null;
  const panoramaUrl = assets.imagery?.pano_url ?? null;
  const thumbnailUrl = assets.thumbnail_url ?? null;

  if (!splatUrls.k100 && !splatUrls.k500 && !splatUrls.full && !colliderMeshUrl && !panoramaUrl) {
    return {
      ok: false,
      code: "bad_response",
      message: `World Labs operation ${meta.operationId} finished but returned no downloadable assets (no splats, mesh or panorama). Check the world at ${PLATFORM_URL}.`,
      operationId: meta.operationId,
    };
  }

  const model = world.generation_input?.model ?? meta.fallbackModel;
  const quality = meta.quality;
  return {
    operationId: meta.operationId,
    worldId: world.id ?? world.world_id ?? null,
    displayName: world.display_name ?? "",
    model,
    quality,
    mode: meta.mode,
    input: meta.input,
    caption: assets.caption ?? null,
    splatUrls,
    colliderMeshUrl,
    panoramaUrl,
    thumbnailUrl,
    estimatedCredits: quality ? QUALITY_TIERS[quality].credits : null,
    license: LICENSE_NOTE,
    attribution: ATTRIBUTION,
  };
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Generate a 3D Gaussian-splat world from a text prompt, an image or a video
 * via the World Labs World API: submit the generation, then poll the
 * long-running operation until it finishes or the bounded deadline expires.
 * With `operationId`, skip submission and only poll (nothing new is billed).
 *
 * Reads `WORLDLABS_API_KEY` from the environment. All error paths return a
 * `GenerateWorldError` rather than throwing, so the MCP dispatcher can render
 * a friendly message without wrapping the call in a try/catch.
 */
export async function generateWorld(options: GenerateWorldOptions): Promise<GenerateWorldResult> {
  // ── Input validation (no network before this passes) ──────────────────────
  const prompt = typeof options?.prompt === "string" ? options.prompt.trim() : undefined;
  const imageUrl = typeof options?.imageUrl === "string" ? options.imageUrl.trim() : undefined;
  const videoUrl = typeof options?.videoUrl === "string" ? options.videoUrl.trim() : undefined;
  const operationIdIn =
    typeof options?.operationId === "string" ? options.operationId.trim() : undefined;
  const hasPrompt = prompt !== undefined && prompt.length > 0;
  const hasImage = imageUrl !== undefined && imageUrl.length > 0;
  const hasVideo = videoUrl !== undefined && videoUrl.length > 0;
  const hasOperation = operationIdIn !== undefined && operationIdIn.length > 0;

  if (hasOperation && (hasPrompt || hasImage || hasVideo)) {
    return {
      ok: false,
      code: "invalid_input",
      message:
        "`operationId` resumes polling an existing generation and cannot be combined with `prompt`, `imageUrl` or `videoUrl`. Pass it alone.",
    };
  }
  if (hasOperation && !/^[A-Za-z0-9_.:-]+$/.test(operationIdIn)) {
    return {
      ok: false,
      code: "invalid_input",
      message: "`operationId` must be the bare id returned by an earlier generate_world call.",
    };
  }
  if (!hasOperation && !hasPrompt && !hasImage && !hasVideo) {
    return {
      ok: false,
      code: "invalid_input",
      message:
        "Provide at least one of `prompt` (text→world), `imageUrl` (image→world) or `videoUrl` (video→world). All three are currently empty.",
    };
  }
  if (hasImage && hasVideo) {
    return {
      ok: false,
      code: "invalid_input",
      message:
        "Provide either `imageUrl` or `videoUrl`, not both. A world is generated from one image (optionally with a guiding `prompt`) or from one video clip.",
    };
  }
  if (hasPrompt && prompt.length > MAX_PROMPT_LENGTH) {
    return {
      ok: false,
      code: "invalid_input",
      message: `\`prompt\` is too long (${prompt.length} chars). Keep it under ${MAX_PROMPT_LENGTH} characters — a few sentences describing the place, its lighting and its mood work best.`,
    };
  }
  if (hasImage && !isHttpsUrl(imageUrl)) {
    return {
      ok: false,
      code: "invalid_input",
      message:
        "`imageUrl` must be a public https:// URL to a JPEG, PNG or WebP image (World Labs downloads it itself). Local paths and http:// URLs are not accepted.",
    };
  }
  if (hasVideo && !isHttpsUrl(videoUrl)) {
    return {
      ok: false,
      code: "invalid_input",
      message:
        "`videoUrl` must be a public https:// URL to an mp4, mov or webm clip of at most 30 seconds and 100 MB (World Labs downloads it itself). Local paths and http:// URLs are not accepted.",
    };
  }
  if (options?.isPanorama && !hasImage) {
    return {
      ok: false,
      code: "invalid_input",
      message: "`isPanorama` only applies to `imageUrl` (a 360° equirectangular image).",
    };
  }

  const quality: WorldQuality =
    options.quality === "standard" || options.quality === "large" ? options.quality : "draft";
  const tier = QUALITY_TIERS[quality];

  const apiKey = process.env[API_KEY_ENV];
  if (!apiKey || apiKey.trim().length === 0) {
    return missingKeyError();
  }

  const headers: Record<string, string> = {
    [API_KEY_HEADER]: apiKey.trim(),
    "Content-Type": "application/json",
    Accept: "application/json",
  };

  const mode: GeneratedWorld["mode"] = hasOperation
    ? "resumed"
    : hasVideo
      ? "video"
      : hasImage
        ? "image"
        : "text";
  const input = hasOperation
    ? (operationIdIn as string)
    : hasVideo
      ? (videoUrl as string)
      : hasImage
        ? (imageUrl as string)
        : (prompt as string);

  // ── 1. Submit the generation (unless resuming) ─────────────────────────────
  let operationId: string;
  let lastOperation: WorldLabsOperation | undefined;

  if (hasOperation) {
    operationId = operationIdIn as string;
  } else {
    const body = buildGenerateBody({
      prompt: hasPrompt ? prompt : undefined,
      imageUrl: hasImage ? imageUrl : undefined,
      isPanorama: hasImage ? options.isPanorama === true : undefined,
      videoUrl: hasVideo ? videoUrl : undefined,
      quality,
      seed: options.seed,
    });

    let submitResponse: Response;
    try {
      submitResponse = await fetch(GENERATE_ENDPOINT, {
        method: "POST",
        headers,
        body: JSON.stringify(body),
      });
    } catch (err) {
      const cause = err instanceof Error ? err.message : String(err);
      return {
        ok: false,
        code: "network",
        message: `Could not reach World Labs (${cause}). Check your internet connection and try again — nothing was billed.`,
      };
    }

    if (!submitResponse.ok) {
      let detail: string | undefined;
      try {
        detail = apiMessage(await submitResponse.json());
      } catch {
        detail = undefined;
      }
      return httpError(submitResponse.status, submitResponse.statusText, detail);
    }

    let submitPayload: WorldLabsOperation;
    try {
      submitPayload = (await submitResponse.json()) as WorldLabsOperation;
    } catch (err) {
      const cause = err instanceof Error ? err.message : String(err);
      return {
        ok: false,
        code: "bad_response",
        message: `World Labs returned invalid JSON: ${cause}`,
      };
    }

    const id = operationIdOf(submitPayload ?? {});
    if (!id) {
      return {
        ok: false,
        code: "bad_response",
        message: "World Labs accepted the request but returned no operation id.",
      };
    }
    operationId = id;
    lastOperation = submitPayload;
  }

  // ── 2. Poll the operation until done (bounded) ─────────────────────────────
  const pollIntervalMs = options.pollIntervalMs ?? DEFAULT_POLL_INTERVAL_MS;
  const timeoutMs = options.timeoutMs ?? tier.timeoutMs;
  const deadline = Date.now() + timeoutMs;
  let lastStatus = "PENDING";
  let lastDescription = "";

  // A submit response that is already done (cached / instant) needs no poll.
  let current: WorldLabsOperation | undefined = lastOperation?.done ? lastOperation : undefined;

  for (;;) {
    if (!current) {
      let pollResponse: Response;
      try {
        pollResponse = await fetch(`${OPERATIONS_ENDPOINT}/${encodeURIComponent(operationId)}`, {
          headers,
        });
      } catch (err) {
        const cause = err instanceof Error ? err.message : String(err);
        return {
          ok: false,
          code: "network",
          message: `Lost connection to World Labs while polling operation ${operationId} (${cause}). The generation is still running on their side — call generate_world again with operationId: "${operationId}" to resume without paying twice.`,
          operationId,
        };
      }

      if (
        pollResponse.status === 401 ||
        pollResponse.status === 402 ||
        pollResponse.status === 403
      ) {
        let detail: string | undefined;
        try {
          detail = apiMessage(await pollResponse.json());
        } catch {
          detail = undefined;
        }
        return { ...httpError(pollResponse.status, pollResponse.statusText, detail), operationId };
      }

      if (pollResponse.status === 404) {
        return {
          ok: false,
          code: "bad_response",
          message: `World Labs knows no operation "${operationId}" (HTTP 404). Check the id, or start a new generation.`,
        };
      }

      // Transient poll hiccups (429 burst, 5xx, malformed JSON) are tolerated:
      // keep polling until the bounded deadline instead of failing the job.
      if (pollResponse.ok) {
        try {
          current = (await pollResponse.json()) as WorldLabsOperation;
        } catch {
          current = undefined;
        }
      }
    }

    if (current) {
      const progress = current.metadata?.progress;
      if (typeof progress?.status === "string") lastStatus = progress.status;
      if (typeof progress?.description === "string") lastDescription = progress.description;

      if (current.done === true) {
        if (current.error !== undefined && current.error !== null) {
          const detail =
            typeof current.error === "string" ? current.error : (current.error.message ?? "");
          return {
            ok: false,
            code: "task_failed",
            message: [
              `World Labs could not generate this world (operation ${operationId})${detail ? `: ${detail}` : "."}`,
              mode === "video"
                ? "Try a steadier clip: one continuous take under 30 s, a fixed focal length, and a slow 180°–360° rotation of the space."
                : mode === "image"
                  ? "Try a clearer, wider source image (or set isPanorama for a 360° shot), or add a short guiding prompt."
                  : "Try rephrasing the prompt — describe the place, its scale, lighting and materials.",
              `Check the operation at ${PLATFORM_URL}.`,
            ].join(" "),
            operationId,
          };
        }
        if (!current.response || typeof current.response !== "object") {
          return {
            ok: false,
            code: "bad_response",
            message: `World Labs operation ${operationId} finished without a world in its response.`,
            operationId,
          };
        }
        const extracted = extractWorld(current.response, {
          operationId,
          quality: hasOperation ? null : quality,
          mode,
          input,
          fallbackModel: hasOperation ? "unknown" : tier.model,
        });
        if ("ok" in extracted) return extracted;
        return { ok: true, world: extracted };
      }
      current = undefined; // not done → poll again after the interval
    }

    if (Date.now() >= deadline) {
      return {
        ok: false,
        code: "timeout",
        message: [
          `World Labs operation ${operationId} did not finish within ${Math.round(timeoutMs / 1000)}s`,
          `(last status: "${lastStatus}"${lastDescription ? ` — ${lastDescription}` : ""}).`,
          "The generation keeps running on World Labs' side and its credits are already committed —",
          `call generate_world again with operationId: "${operationId}" to pick up the result without generating (and paying) twice.`,
        ].join(" "),
        operationId,
      };
    }

    await sleep(pollIntervalMs);
  }
}

/**
 * Render a `GenerateWorldResult` as the markdown text block the MCP
 * dispatcher returns to the client. Kept here (not in handler.ts) so unit
 * tests can verify formatting without touching the dispatch layer.
 */
export function formatGenerateWorldResult(result: GenerateWorldResult): string {
  if (!result.ok) {
    return result.message;
  }

  const w = result.world;
  const sourceLabel =
    w.mode === "text"
      ? "Prompt"
      : w.mode === "image"
        ? "Source image"
        : w.mode === "video"
          ? "Source video"
          : "Resumed operation";
  const tierLabel = w.quality ? QUALITY_TIERS[w.quality].label : w.model;
  const phoneSplat = w.splatUrls.k100 ?? w.splatUrls.k500 ?? w.splatUrls.full ?? "";

  const lines: string[] = [
    `## Generated 3D world (${tierLabel})`,
    "",
    ...(w.displayName
      ? [`- **World:** ${w.displayName}${w.worldId ? ` (\`${w.worldId}\`)` : ""}`]
      : []),
    ...(w.caption ? [`- **Caption:** ${w.caption}`] : []),
    `- **${sourceLabel}:** ${w.input}`,
    `- **Model:** ${w.model}`,
    `- **Operation ID:** \`${w.operationId}\``,
    ...(w.estimatedCredits ? [`- **World Labs credits (price list):** ${w.estimatedCredits}`] : []),
    "",
    "### Assets",
    "",
    "Download every URL you keep **now** and self-host it: World Labs asset links are signed and stop working after a while.",
    "",
    ...(w.colliderMeshUrl
      ? [
          `- **Collider mesh (GLB, 100–200k triangles):** ${w.colliderMeshUrl} — loads with \`rememberModelInstance(modelLoader, …)\` on every SceneView platform; use it for physics and hit-tests, or as a plain mesh preview.`,
        ]
      : []),
    ...(w.panoramaUrl
      ? [
          `- **360° panorama (equirectangular image, 2560×1280):** ${w.panoramaUrl} — SDR, so map it onto an inverted \`SphereNode\` with \`materialLoader.createImageInstance(...)\` rather than feeding it to the HDR environment loader.`,
        ]
      : []),
    ...(w.splatUrls.k100
      ? [
          `- **Splats, 100k (.spz) — the tier for phones:** ${w.splatUrls.k100} — the current Android renderer re-sorts on the CPU and re-uploads the cloud while the camera moves, so 500k is beyond a phone's budget; the file also carries degree-3 spherical harmonics the parser discards.`,
        ]
      : []),
    ...(w.splatUrls.k500 ? [`- **Splats, 500k (.spz) — desktop / web:** ${w.splatUrls.k500}`] : []),
    ...(w.splatUrls.full ? [`- **Splats, full (~2M, .spz):** ${w.splatUrls.full}`] : []),
    ...(w.thumbnailUrl ? [`- **Thumbnail:** ${w.thumbnailUrl}`] : []),
    `- **License:** ${w.license}`,
    `- **Generator:** ${w.attribution}`,
    "",
    "### Load the splats in SceneView",
    "",
    "Marble worlds use the OpenCV convention (+y down, +z forward); Filament is +y up, −z forward. Rotate the node 180° about X. `SplatParser` reads gzip SPZ v2/v3 and keeps only the degree-0 colour band, so colours look a little flatter than in the Marble viewer — verify the first world you load, and fall back to the collider GLB if the file is rejected (SPZ v4/NGSP is not supported yet).",
    "",
    "```kotlin",
    "// Android — bytes downloaded (off the main thread) from the 100k .spz URL above",
    "val cloud = rememberSplatCloud(spzBytes) { SplatParser.parse(spzBytes) }",
    "var cameraPosition by remember { mutableStateOf(Position()) }",
    "SceneView(cameraNode = cameraNode, onFrame = { cameraPosition = cameraNode.worldPosition }) {",
    "    SplatNode(",
    "        splatCloud = cloud,",
    "        rotation = Rotation(x = 180f),                 // OpenCV → Filament",
    "        cameraPositionProvider = { cameraPosition },   // back-to-front sort while orbiting",
    "    )",
    "}",
    "```",
    "",
    "```js",
    `// Web — the viewer fetches and parses the file itself`,
    `const world = await sv.addSplatNode(${JSON.stringify(phoneSplat || "https://…/world_100k.spz")});`,
    "world.setRotation(180, 0, 0);   // OpenCV → Filament",
    "```",
    "",
    'iOS has no Gaussian-splat renderer yet (tracked in #2646) — load the collider GLB there. See the llms.txt recipe "Generate a 3D world with AI (World Labs) and walk through it".',
  ];
  return lines.join("\n");
}
